/**
 * Cbr_Ifc_Ws_Out_Dados_LaudoRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.meta4.schemas.types;

public class Cbr_Ifc_Ws_Out_Dados_LaudoRecord  implements java.io.Serializable {
    private java.util.Calendar cbr_Dt_Conclusao;

    private java.lang.String cbr_Id_Parecer_Fm;

    private java.lang.String cbr_N_Parecer_Fm;

    private java.util.Calendar dt_Last_Update;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    public Cbr_Ifc_Ws_Out_Dados_LaudoRecord() {
    }

    public Cbr_Ifc_Ws_Out_Dados_LaudoRecord(
           java.util.Calendar cbr_Dt_Conclusao,
           java.lang.String cbr_Id_Parecer_Fm,
           java.lang.String cbr_N_Parecer_Fm,
           java.util.Calendar dt_Last_Update,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete) {
           this.cbr_Dt_Conclusao = cbr_Dt_Conclusao;
           this.cbr_Id_Parecer_Fm = cbr_Id_Parecer_Fm;
           this.cbr_N_Parecer_Fm = cbr_N_Parecer_Fm;
           this.dt_Last_Update = dt_Last_Update;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the cbr_Dt_Conclusao value for this Cbr_Ifc_Ws_Out_Dados_LaudoRecord.
     * 
     * @return cbr_Dt_Conclusao
     */
    public java.util.Calendar getCbr_Dt_Conclusao() {
        return cbr_Dt_Conclusao;
    }


    /**
     * Sets the cbr_Dt_Conclusao value for this Cbr_Ifc_Ws_Out_Dados_LaudoRecord.
     * 
     * @param cbr_Dt_Conclusao
     */
    public void setCbr_Dt_Conclusao(java.util.Calendar cbr_Dt_Conclusao) {
        this.cbr_Dt_Conclusao = cbr_Dt_Conclusao;
    }


    /**
     * Gets the cbr_Id_Parecer_Fm value for this Cbr_Ifc_Ws_Out_Dados_LaudoRecord.
     * 
     * @return cbr_Id_Parecer_Fm
     */
    public java.lang.String getCbr_Id_Parecer_Fm() {
        return cbr_Id_Parecer_Fm;
    }


    /**
     * Sets the cbr_Id_Parecer_Fm value for this Cbr_Ifc_Ws_Out_Dados_LaudoRecord.
     * 
     * @param cbr_Id_Parecer_Fm
     */
    public void setCbr_Id_Parecer_Fm(java.lang.String cbr_Id_Parecer_Fm) {
        this.cbr_Id_Parecer_Fm = cbr_Id_Parecer_Fm;
    }


    /**
     * Gets the cbr_N_Parecer_Fm value for this Cbr_Ifc_Ws_Out_Dados_LaudoRecord.
     * 
     * @return cbr_N_Parecer_Fm
     */
    public java.lang.String getCbr_N_Parecer_Fm() {
        return cbr_N_Parecer_Fm;
    }


    /**
     * Sets the cbr_N_Parecer_Fm value for this Cbr_Ifc_Ws_Out_Dados_LaudoRecord.
     * 
     * @param cbr_N_Parecer_Fm
     */
    public void setCbr_N_Parecer_Fm(java.lang.String cbr_N_Parecer_Fm) {
        this.cbr_N_Parecer_Fm = cbr_N_Parecer_Fm;
    }


    /**
     * Gets the dt_Last_Update value for this Cbr_Ifc_Ws_Out_Dados_LaudoRecord.
     * 
     * @return dt_Last_Update
     */
    public java.util.Calendar getDt_Last_Update() {
        return dt_Last_Update;
    }


    /**
     * Sets the dt_Last_Update value for this Cbr_Ifc_Ws_Out_Dados_LaudoRecord.
     * 
     * @param dt_Last_Update
     */
    public void setDt_Last_Update(java.util.Calendar dt_Last_Update) {
        this.dt_Last_Update = dt_Last_Update;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Cbr_Ifc_Ws_Out_Dados_LaudoRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Cbr_Ifc_Ws_Out_Dados_LaudoRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Cbr_Ifc_Ws_Out_Dados_LaudoRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Cbr_Ifc_Ws_Out_Dados_LaudoRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Cbr_Ifc_Ws_Out_Dados_LaudoRecord)) return false;
        Cbr_Ifc_Ws_Out_Dados_LaudoRecord other = (Cbr_Ifc_Ws_Out_Dados_LaudoRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.cbr_Dt_Conclusao==null && other.getCbr_Dt_Conclusao()==null) || 
             (this.cbr_Dt_Conclusao!=null &&
              this.cbr_Dt_Conclusao.equals(other.getCbr_Dt_Conclusao()))) &&
            ((this.cbr_Id_Parecer_Fm==null && other.getCbr_Id_Parecer_Fm()==null) || 
             (this.cbr_Id_Parecer_Fm!=null &&
              this.cbr_Id_Parecer_Fm.equals(other.getCbr_Id_Parecer_Fm()))) &&
            ((this.cbr_N_Parecer_Fm==null && other.getCbr_N_Parecer_Fm()==null) || 
             (this.cbr_N_Parecer_Fm!=null &&
              this.cbr_N_Parecer_Fm.equals(other.getCbr_N_Parecer_Fm()))) &&
            ((this.dt_Last_Update==null && other.getDt_Last_Update()==null) || 
             (this.dt_Last_Update!=null &&
              this.dt_Last_Update.equals(other.getDt_Last_Update()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete();
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCbr_Dt_Conclusao() != null) {
            _hashCode += getCbr_Dt_Conclusao().hashCode();
        }
        if (getCbr_Id_Parecer_Fm() != null) {
            _hashCode += getCbr_Id_Parecer_Fm().hashCode();
        }
        if (getCbr_N_Parecer_Fm() != null) {
            _hashCode += getCbr_N_Parecer_Fm().hashCode();
        }
        if (getDt_Last_Update() != null) {
            _hashCode += getDt_Last_Update().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Cbr_Ifc_Ws_Out_Dados_LaudoRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Cbr_Ifc_Ws_Out_Dados_LaudoRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Dt_Conclusao");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Dt_Conclusao"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Id_Parecer_Fm");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Id_Parecer_Fm"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_N_Parecer_Fm");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_N_Parecer_Fm"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("dt_Last_Update");
        elemField.setXmlName(new javax.xml.namespace.QName("", "dt_Last_Update"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
