/**
 * Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.meta4.schemas.types;

public class Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord  implements java.io.Serializable {
    private java.lang.String cbr_Cpf;

    private java.util.Calendar cbr_Dt_Emis_Cident;

    private java.util.Calendar cbr_Dt_Morte;

    private java.lang.String cbr_Id_Geo_Div_Te;

    private java.lang.String cbr_Id_Sub_Gdiv_Te;

    private java.lang.String cbr_Id_Uf_Cident;

    private java.lang.String cbr_N_Mae;

    private java.lang.String cbr_N_Pai;

    private java.lang.String cbr_Nro_Cart_Ident;

    private java.lang.String cbr_Nro_Sic;

    private java.lang.String cbr_Nro_T_Eleitor;

    private java.lang.Double cbr_Num_Matricula;

    private java.lang.String cbr_Org_Emis_Cident;

    private java.lang.String cbr_Pis_Pasep;

    private java.lang.String cbr_Sec_T_Eleit;

    private java.lang.String cbr_Zona_T_Eleit;

    private java.lang.String id_Organization;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String nm_Organization;

    private java.lang.String sco_Gb_Name;

    private java.util.Calendar std_Dt_Birth;

    private java.lang.String std_Email;

    private java.lang.String std_Id_Hr;

    private java.lang.Double std_Id_Marital_Stat;

    private java.lang.Double std_Or_Hr_Period;

    private java.lang.String std_Zip_Code;

    public Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord() {
    }

    public Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord(
           java.lang.String cbr_Cpf,
           java.util.Calendar cbr_Dt_Emis_Cident,
           java.util.Calendar cbr_Dt_Morte,
           java.lang.String cbr_Id_Geo_Div_Te,
           java.lang.String cbr_Id_Sub_Gdiv_Te,
           java.lang.String cbr_Id_Uf_Cident,
           java.lang.String cbr_N_Mae,
           java.lang.String cbr_N_Pai,
           java.lang.String cbr_Nro_Cart_Ident,
           java.lang.String cbr_Nro_Sic,
           java.lang.String cbr_Nro_T_Eleitor,
           java.lang.Double cbr_Num_Matricula,
           java.lang.String cbr_Org_Emis_Cident,
           java.lang.String cbr_Pis_Pasep,
           java.lang.String cbr_Sec_T_Eleit,
           java.lang.String cbr_Zona_T_Eleit,
           java.lang.String id_Organization,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String nm_Organization,
           java.lang.String sco_Gb_Name,
           java.util.Calendar std_Dt_Birth,
           java.lang.String std_Email,
           java.lang.String std_Id_Hr,
           java.lang.Double std_Id_Marital_Stat,
           java.lang.Double std_Or_Hr_Period,
           java.lang.String std_Zip_Code) {
           this.cbr_Cpf = cbr_Cpf;
           this.cbr_Dt_Emis_Cident = cbr_Dt_Emis_Cident;
           this.cbr_Dt_Morte = cbr_Dt_Morte;
           this.cbr_Id_Geo_Div_Te = cbr_Id_Geo_Div_Te;
           this.cbr_Id_Sub_Gdiv_Te = cbr_Id_Sub_Gdiv_Te;
           this.cbr_Id_Uf_Cident = cbr_Id_Uf_Cident;
           this.cbr_N_Mae = cbr_N_Mae;
           this.cbr_N_Pai = cbr_N_Pai;
           this.cbr_Nro_Cart_Ident = cbr_Nro_Cart_Ident;
           this.cbr_Nro_Sic = cbr_Nro_Sic;
           this.cbr_Nro_T_Eleitor = cbr_Nro_T_Eleitor;
           this.cbr_Num_Matricula = cbr_Num_Matricula;
           this.cbr_Org_Emis_Cident = cbr_Org_Emis_Cident;
           this.cbr_Pis_Pasep = cbr_Pis_Pasep;
           this.cbr_Sec_T_Eleit = cbr_Sec_T_Eleit;
           this.cbr_Zona_T_Eleit = cbr_Zona_T_Eleit;
           this.id_Organization = id_Organization;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.nm_Organization = nm_Organization;
           this.sco_Gb_Name = sco_Gb_Name;
           this.std_Dt_Birth = std_Dt_Birth;
           this.std_Email = std_Email;
           this.std_Id_Hr = std_Id_Hr;
           this.std_Id_Marital_Stat = std_Id_Marital_Stat;
           this.std_Or_Hr_Period = std_Or_Hr_Period;
           this.std_Zip_Code = std_Zip_Code;
    }


    /**
     * Gets the cbr_Cpf value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Cpf
     */
    public java.lang.String getCbr_Cpf() {
        return cbr_Cpf;
    }


    /**
     * Sets the cbr_Cpf value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Cpf
     */
    public void setCbr_Cpf(java.lang.String cbr_Cpf) {
        this.cbr_Cpf = cbr_Cpf;
    }


    /**
     * Gets the cbr_Dt_Emis_Cident value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Dt_Emis_Cident
     */
    public java.util.Calendar getCbr_Dt_Emis_Cident() {
        return cbr_Dt_Emis_Cident;
    }


    /**
     * Sets the cbr_Dt_Emis_Cident value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Dt_Emis_Cident
     */
    public void setCbr_Dt_Emis_Cident(java.util.Calendar cbr_Dt_Emis_Cident) {
        this.cbr_Dt_Emis_Cident = cbr_Dt_Emis_Cident;
    }


    /**
     * Gets the cbr_Dt_Morte value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Dt_Morte
     */
    public java.util.Calendar getCbr_Dt_Morte() {
        return cbr_Dt_Morte;
    }


    /**
     * Sets the cbr_Dt_Morte value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Dt_Morte
     */
    public void setCbr_Dt_Morte(java.util.Calendar cbr_Dt_Morte) {
        this.cbr_Dt_Morte = cbr_Dt_Morte;
    }


    /**
     * Gets the cbr_Id_Geo_Div_Te value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Id_Geo_Div_Te
     */
    public java.lang.String getCbr_Id_Geo_Div_Te() {
        return cbr_Id_Geo_Div_Te;
    }


    /**
     * Sets the cbr_Id_Geo_Div_Te value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Id_Geo_Div_Te
     */
    public void setCbr_Id_Geo_Div_Te(java.lang.String cbr_Id_Geo_Div_Te) {
        this.cbr_Id_Geo_Div_Te = cbr_Id_Geo_Div_Te;
    }


    /**
     * Gets the cbr_Id_Sub_Gdiv_Te value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Id_Sub_Gdiv_Te
     */
    public java.lang.String getCbr_Id_Sub_Gdiv_Te() {
        return cbr_Id_Sub_Gdiv_Te;
    }


    /**
     * Sets the cbr_Id_Sub_Gdiv_Te value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Id_Sub_Gdiv_Te
     */
    public void setCbr_Id_Sub_Gdiv_Te(java.lang.String cbr_Id_Sub_Gdiv_Te) {
        this.cbr_Id_Sub_Gdiv_Te = cbr_Id_Sub_Gdiv_Te;
    }


    /**
     * Gets the cbr_Id_Uf_Cident value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Id_Uf_Cident
     */
    public java.lang.String getCbr_Id_Uf_Cident() {
        return cbr_Id_Uf_Cident;
    }


    /**
     * Sets the cbr_Id_Uf_Cident value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Id_Uf_Cident
     */
    public void setCbr_Id_Uf_Cident(java.lang.String cbr_Id_Uf_Cident) {
        this.cbr_Id_Uf_Cident = cbr_Id_Uf_Cident;
    }


    /**
     * Gets the cbr_N_Mae value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_N_Mae
     */
    public java.lang.String getCbr_N_Mae() {
        return cbr_N_Mae;
    }


    /**
     * Sets the cbr_N_Mae value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_N_Mae
     */
    public void setCbr_N_Mae(java.lang.String cbr_N_Mae) {
        this.cbr_N_Mae = cbr_N_Mae;
    }


    /**
     * Gets the cbr_N_Pai value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_N_Pai
     */
    public java.lang.String getCbr_N_Pai() {
        return cbr_N_Pai;
    }


    /**
     * Sets the cbr_N_Pai value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_N_Pai
     */
    public void setCbr_N_Pai(java.lang.String cbr_N_Pai) {
        this.cbr_N_Pai = cbr_N_Pai;
    }


    /**
     * Gets the cbr_Nro_Cart_Ident value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Nro_Cart_Ident
     */
    public java.lang.String getCbr_Nro_Cart_Ident() {
        return cbr_Nro_Cart_Ident;
    }


    /**
     * Sets the cbr_Nro_Cart_Ident value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Nro_Cart_Ident
     */
    public void setCbr_Nro_Cart_Ident(java.lang.String cbr_Nro_Cart_Ident) {
        this.cbr_Nro_Cart_Ident = cbr_Nro_Cart_Ident;
    }


    /**
     * Gets the cbr_Nro_Sic value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Nro_Sic
     */
    public java.lang.String getCbr_Nro_Sic() {
        return cbr_Nro_Sic;
    }


    /**
     * Sets the cbr_Nro_Sic value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Nro_Sic
     */
    public void setCbr_Nro_Sic(java.lang.String cbr_Nro_Sic) {
        this.cbr_Nro_Sic = cbr_Nro_Sic;
    }


    /**
     * Gets the cbr_Nro_T_Eleitor value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Nro_T_Eleitor
     */
    public java.lang.String getCbr_Nro_T_Eleitor() {
        return cbr_Nro_T_Eleitor;
    }


    /**
     * Sets the cbr_Nro_T_Eleitor value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Nro_T_Eleitor
     */
    public void setCbr_Nro_T_Eleitor(java.lang.String cbr_Nro_T_Eleitor) {
        this.cbr_Nro_T_Eleitor = cbr_Nro_T_Eleitor;
    }


    /**
     * Gets the cbr_Num_Matricula value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Num_Matricula
     */
    public java.lang.Double getCbr_Num_Matricula() {
        return cbr_Num_Matricula;
    }


    /**
     * Sets the cbr_Num_Matricula value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Num_Matricula
     */
    public void setCbr_Num_Matricula(java.lang.Double cbr_Num_Matricula) {
        this.cbr_Num_Matricula = cbr_Num_Matricula;
    }


    /**
     * Gets the cbr_Org_Emis_Cident value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Org_Emis_Cident
     */
    public java.lang.String getCbr_Org_Emis_Cident() {
        return cbr_Org_Emis_Cident;
    }


    /**
     * Sets the cbr_Org_Emis_Cident value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Org_Emis_Cident
     */
    public void setCbr_Org_Emis_Cident(java.lang.String cbr_Org_Emis_Cident) {
        this.cbr_Org_Emis_Cident = cbr_Org_Emis_Cident;
    }


    /**
     * Gets the cbr_Pis_Pasep value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Pis_Pasep
     */
    public java.lang.String getCbr_Pis_Pasep() {
        return cbr_Pis_Pasep;
    }


    /**
     * Sets the cbr_Pis_Pasep value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Pis_Pasep
     */
    public void setCbr_Pis_Pasep(java.lang.String cbr_Pis_Pasep) {
        this.cbr_Pis_Pasep = cbr_Pis_Pasep;
    }


    /**
     * Gets the cbr_Sec_T_Eleit value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Sec_T_Eleit
     */
    public java.lang.String getCbr_Sec_T_Eleit() {
        return cbr_Sec_T_Eleit;
    }


    /**
     * Sets the cbr_Sec_T_Eleit value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Sec_T_Eleit
     */
    public void setCbr_Sec_T_Eleit(java.lang.String cbr_Sec_T_Eleit) {
        this.cbr_Sec_T_Eleit = cbr_Sec_T_Eleit;
    }


    /**
     * Gets the cbr_Zona_T_Eleit value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return cbr_Zona_T_Eleit
     */
    public java.lang.String getCbr_Zona_T_Eleit() {
        return cbr_Zona_T_Eleit;
    }


    /**
     * Sets the cbr_Zona_T_Eleit value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param cbr_Zona_T_Eleit
     */
    public void setCbr_Zona_T_Eleit(java.lang.String cbr_Zona_T_Eleit) {
        this.cbr_Zona_T_Eleit = cbr_Zona_T_Eleit;
    }


    /**
     * Gets the id_Organization value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return id_Organization
     */
    public java.lang.String getId_Organization() {
        return id_Organization;
    }


    /**
     * Sets the id_Organization value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param id_Organization
     */
    public void setId_Organization(java.lang.String id_Organization) {
        this.id_Organization = id_Organization;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the nm_Organization value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return nm_Organization
     */
    public java.lang.String getNm_Organization() {
        return nm_Organization;
    }


    /**
     * Sets the nm_Organization value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param nm_Organization
     */
    public void setNm_Organization(java.lang.String nm_Organization) {
        this.nm_Organization = nm_Organization;
    }


    /**
     * Gets the sco_Gb_Name value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return sco_Gb_Name
     */
    public java.lang.String getSco_Gb_Name() {
        return sco_Gb_Name;
    }


    /**
     * Sets the sco_Gb_Name value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param sco_Gb_Name
     */
    public void setSco_Gb_Name(java.lang.String sco_Gb_Name) {
        this.sco_Gb_Name = sco_Gb_Name;
    }


    /**
     * Gets the std_Dt_Birth value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return std_Dt_Birth
     */
    public java.util.Calendar getStd_Dt_Birth() {
        return std_Dt_Birth;
    }


    /**
     * Sets the std_Dt_Birth value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param std_Dt_Birth
     */
    public void setStd_Dt_Birth(java.util.Calendar std_Dt_Birth) {
        this.std_Dt_Birth = std_Dt_Birth;
    }


    /**
     * Gets the std_Email value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return std_Email
     */
    public java.lang.String getStd_Email() {
        return std_Email;
    }


    /**
     * Sets the std_Email value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param std_Email
     */
    public void setStd_Email(java.lang.String std_Email) {
        this.std_Email = std_Email;
    }


    /**
     * Gets the std_Id_Hr value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return std_Id_Hr
     */
    public java.lang.String getStd_Id_Hr() {
        return std_Id_Hr;
    }


    /**
     * Sets the std_Id_Hr value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param std_Id_Hr
     */
    public void setStd_Id_Hr(java.lang.String std_Id_Hr) {
        this.std_Id_Hr = std_Id_Hr;
    }


    /**
     * Gets the std_Id_Marital_Stat value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return std_Id_Marital_Stat
     */
    public java.lang.Double getStd_Id_Marital_Stat() {
        return std_Id_Marital_Stat;
    }


    /**
     * Sets the std_Id_Marital_Stat value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param std_Id_Marital_Stat
     */
    public void setStd_Id_Marital_Stat(java.lang.Double std_Id_Marital_Stat) {
        this.std_Id_Marital_Stat = std_Id_Marital_Stat;
    }


    /**
     * Gets the std_Or_Hr_Period value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return std_Or_Hr_Period
     */
    public java.lang.Double getStd_Or_Hr_Period() {
        return std_Or_Hr_Period;
    }


    /**
     * Sets the std_Or_Hr_Period value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param std_Or_Hr_Period
     */
    public void setStd_Or_Hr_Period(java.lang.Double std_Or_Hr_Period) {
        this.std_Or_Hr_Period = std_Or_Hr_Period;
    }


    /**
     * Gets the std_Zip_Code value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @return std_Zip_Code
     */
    public java.lang.String getStd_Zip_Code() {
        return std_Zip_Code;
    }


    /**
     * Sets the std_Zip_Code value for this Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.
     * 
     * @param std_Zip_Code
     */
    public void setStd_Zip_Code(java.lang.String std_Zip_Code) {
        this.std_Zip_Code = std_Zip_Code;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord)) return false;
        Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord other = (Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.cbr_Cpf==null && other.getCbr_Cpf()==null) || 
             (this.cbr_Cpf!=null &&
              this.cbr_Cpf.equals(other.getCbr_Cpf()))) &&
            ((this.cbr_Dt_Emis_Cident==null && other.getCbr_Dt_Emis_Cident()==null) || 
             (this.cbr_Dt_Emis_Cident!=null &&
              this.cbr_Dt_Emis_Cident.equals(other.getCbr_Dt_Emis_Cident()))) &&
            ((this.cbr_Dt_Morte==null && other.getCbr_Dt_Morte()==null) || 
             (this.cbr_Dt_Morte!=null &&
              this.cbr_Dt_Morte.equals(other.getCbr_Dt_Morte()))) &&
            ((this.cbr_Id_Geo_Div_Te==null && other.getCbr_Id_Geo_Div_Te()==null) || 
             (this.cbr_Id_Geo_Div_Te!=null &&
              this.cbr_Id_Geo_Div_Te.equals(other.getCbr_Id_Geo_Div_Te()))) &&
            ((this.cbr_Id_Sub_Gdiv_Te==null && other.getCbr_Id_Sub_Gdiv_Te()==null) || 
             (this.cbr_Id_Sub_Gdiv_Te!=null &&
              this.cbr_Id_Sub_Gdiv_Te.equals(other.getCbr_Id_Sub_Gdiv_Te()))) &&
            ((this.cbr_Id_Uf_Cident==null && other.getCbr_Id_Uf_Cident()==null) || 
             (this.cbr_Id_Uf_Cident!=null &&
              this.cbr_Id_Uf_Cident.equals(other.getCbr_Id_Uf_Cident()))) &&
            ((this.cbr_N_Mae==null && other.getCbr_N_Mae()==null) || 
             (this.cbr_N_Mae!=null &&
              this.cbr_N_Mae.equals(other.getCbr_N_Mae()))) &&
            ((this.cbr_N_Pai==null && other.getCbr_N_Pai()==null) || 
             (this.cbr_N_Pai!=null &&
              this.cbr_N_Pai.equals(other.getCbr_N_Pai()))) &&
            ((this.cbr_Nro_Cart_Ident==null && other.getCbr_Nro_Cart_Ident()==null) || 
             (this.cbr_Nro_Cart_Ident!=null &&
              this.cbr_Nro_Cart_Ident.equals(other.getCbr_Nro_Cart_Ident()))) &&
            ((this.cbr_Nro_Sic==null && other.getCbr_Nro_Sic()==null) || 
             (this.cbr_Nro_Sic!=null &&
              this.cbr_Nro_Sic.equals(other.getCbr_Nro_Sic()))) &&
            ((this.cbr_Nro_T_Eleitor==null && other.getCbr_Nro_T_Eleitor()==null) || 
             (this.cbr_Nro_T_Eleitor!=null &&
              this.cbr_Nro_T_Eleitor.equals(other.getCbr_Nro_T_Eleitor()))) &&
            ((this.cbr_Num_Matricula==null && other.getCbr_Num_Matricula()==null) || 
             (this.cbr_Num_Matricula!=null &&
              this.cbr_Num_Matricula.equals(other.getCbr_Num_Matricula()))) &&
            ((this.cbr_Org_Emis_Cident==null && other.getCbr_Org_Emis_Cident()==null) || 
             (this.cbr_Org_Emis_Cident!=null &&
              this.cbr_Org_Emis_Cident.equals(other.getCbr_Org_Emis_Cident()))) &&
            ((this.cbr_Pis_Pasep==null && other.getCbr_Pis_Pasep()==null) || 
             (this.cbr_Pis_Pasep!=null &&
              this.cbr_Pis_Pasep.equals(other.getCbr_Pis_Pasep()))) &&
            ((this.cbr_Sec_T_Eleit==null && other.getCbr_Sec_T_Eleit()==null) || 
             (this.cbr_Sec_T_Eleit!=null &&
              this.cbr_Sec_T_Eleit.equals(other.getCbr_Sec_T_Eleit()))) &&
            ((this.cbr_Zona_T_Eleit==null && other.getCbr_Zona_T_Eleit()==null) || 
             (this.cbr_Zona_T_Eleit!=null &&
              this.cbr_Zona_T_Eleit.equals(other.getCbr_Zona_T_Eleit()))) &&
            ((this.id_Organization==null && other.getId_Organization()==null) || 
             (this.id_Organization!=null &&
              this.id_Organization.equals(other.getId_Organization()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.nm_Organization==null && other.getNm_Organization()==null) || 
             (this.nm_Organization!=null &&
              this.nm_Organization.equals(other.getNm_Organization()))) &&
            ((this.sco_Gb_Name==null && other.getSco_Gb_Name()==null) || 
             (this.sco_Gb_Name!=null &&
              this.sco_Gb_Name.equals(other.getSco_Gb_Name()))) &&
            ((this.std_Dt_Birth==null && other.getStd_Dt_Birth()==null) || 
             (this.std_Dt_Birth!=null &&
              this.std_Dt_Birth.equals(other.getStd_Dt_Birth()))) &&
            ((this.std_Email==null && other.getStd_Email()==null) || 
             (this.std_Email!=null &&
              this.std_Email.equals(other.getStd_Email()))) &&
            ((this.std_Id_Hr==null && other.getStd_Id_Hr()==null) || 
             (this.std_Id_Hr!=null &&
              this.std_Id_Hr.equals(other.getStd_Id_Hr()))) &&
            ((this.std_Id_Marital_Stat==null && other.getStd_Id_Marital_Stat()==null) || 
             (this.std_Id_Marital_Stat!=null &&
              this.std_Id_Marital_Stat.equals(other.getStd_Id_Marital_Stat()))) &&
            ((this.std_Or_Hr_Period==null && other.getStd_Or_Hr_Period()==null) || 
             (this.std_Or_Hr_Period!=null &&
              this.std_Or_Hr_Period.equals(other.getStd_Or_Hr_Period()))) &&
            ((this.std_Zip_Code==null && other.getStd_Zip_Code()==null) || 
             (this.std_Zip_Code!=null &&
              this.std_Zip_Code.equals(other.getStd_Zip_Code())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCbr_Cpf() != null) {
            _hashCode += getCbr_Cpf().hashCode();
        }
        if (getCbr_Dt_Emis_Cident() != null) {
            _hashCode += getCbr_Dt_Emis_Cident().hashCode();
        }
        if (getCbr_Dt_Morte() != null) {
            _hashCode += getCbr_Dt_Morte().hashCode();
        }
        if (getCbr_Id_Geo_Div_Te() != null) {
            _hashCode += getCbr_Id_Geo_Div_Te().hashCode();
        }
        if (getCbr_Id_Sub_Gdiv_Te() != null) {
            _hashCode += getCbr_Id_Sub_Gdiv_Te().hashCode();
        }
        if (getCbr_Id_Uf_Cident() != null) {
            _hashCode += getCbr_Id_Uf_Cident().hashCode();
        }
        if (getCbr_N_Mae() != null) {
            _hashCode += getCbr_N_Mae().hashCode();
        }
        if (getCbr_N_Pai() != null) {
            _hashCode += getCbr_N_Pai().hashCode();
        }
        if (getCbr_Nro_Cart_Ident() != null) {
            _hashCode += getCbr_Nro_Cart_Ident().hashCode();
        }
        if (getCbr_Nro_Sic() != null) {
            _hashCode += getCbr_Nro_Sic().hashCode();
        }
        if (getCbr_Nro_T_Eleitor() != null) {
            _hashCode += getCbr_Nro_T_Eleitor().hashCode();
        }
        if (getCbr_Num_Matricula() != null) {
            _hashCode += getCbr_Num_Matricula().hashCode();
        }
        if (getCbr_Org_Emis_Cident() != null) {
            _hashCode += getCbr_Org_Emis_Cident().hashCode();
        }
        if (getCbr_Pis_Pasep() != null) {
            _hashCode += getCbr_Pis_Pasep().hashCode();
        }
        if (getCbr_Sec_T_Eleit() != null) {
            _hashCode += getCbr_Sec_T_Eleit().hashCode();
        }
        if (getCbr_Zona_T_Eleit() != null) {
            _hashCode += getCbr_Zona_T_Eleit().hashCode();
        }
        if (getId_Organization() != null) {
            _hashCode += getId_Organization().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getNm_Organization() != null) {
            _hashCode += getNm_Organization().hashCode();
        }
        if (getSco_Gb_Name() != null) {
            _hashCode += getSco_Gb_Name().hashCode();
        }
        if (getStd_Dt_Birth() != null) {
            _hashCode += getStd_Dt_Birth().hashCode();
        }
        if (getStd_Email() != null) {
            _hashCode += getStd_Email().hashCode();
        }
        if (getStd_Id_Hr() != null) {
            _hashCode += getStd_Id_Hr().hashCode();
        }
        if (getStd_Id_Marital_Stat() != null) {
            _hashCode += getStd_Id_Marital_Stat().hashCode();
        }
        if (getStd_Or_Hr_Period() != null) {
            _hashCode += getStd_Or_Hr_Period().hashCode();
        }
        if (getStd_Zip_Code() != null) {
            _hashCode += getStd_Zip_Code().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Cbr_Ifc_Ws_Out_Cad_Pessoa_SimpRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Cpf");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Cpf"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Dt_Emis_Cident");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Dt_Emis_Cident"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Dt_Morte");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Dt_Morte"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Id_Geo_Div_Te");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Id_Geo_Div_Te"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Id_Sub_Gdiv_Te");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Id_Sub_Gdiv_Te"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Id_Uf_Cident");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Id_Uf_Cident"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_N_Mae");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_N_Mae"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_N_Pai");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_N_Pai"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Nro_Cart_Ident");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Nro_Cart_Ident"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Nro_Sic");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Nro_Sic"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Nro_T_Eleitor");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Nro_T_Eleitor"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Num_Matricula");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Num_Matricula"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Org_Emis_Cident");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Org_Emis_Cident"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Pis_Pasep");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Pis_Pasep"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Sec_T_Eleit");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Sec_T_Eleit"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Zona_T_Eleit");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Zona_T_Eleit"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("id_Organization");
        elemField.setXmlName(new javax.xml.namespace.QName("", "id_Organization"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("nm_Organization");
        elemField.setXmlName(new javax.xml.namespace.QName("", "nm_Organization"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Gb_Name");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Gb_Name"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Dt_Birth");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Dt_Birth"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Email");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Email"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Hr");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Hr"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Marital_Stat");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Marital_Stat"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Or_Hr_Period");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Or_Hr_Period"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Zip_Code");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Zip_Code"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
