/**
 * Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.meta4.schemas.types;

public class Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord  implements java.io.Serializable {
    private java.lang.Double ano_Ato_Ini;

    private java.util.Calendar cbr_Dt_End;

    private java.util.Calendar cbr_Dt_Start;

    private java.lang.Double cbr_Id_Tp_Afast;

    private java.lang.String cbr_N_Tp_Afast;

    private java.lang.String cbr_N_Tp_Remuner;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.Double numero_Ato_Ini;

    private java.lang.String tipo_Ato;

    public Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord() {
    }

    public Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord(
           java.lang.Double ano_Ato_Ini,
           java.util.Calendar cbr_Dt_End,
           java.util.Calendar cbr_Dt_Start,
           java.lang.Double cbr_Id_Tp_Afast,
           java.lang.String cbr_N_Tp_Afast,
           java.lang.String cbr_N_Tp_Remuner,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.Double numero_Ato_Ini,
           java.lang.String tipo_Ato) {
           this.ano_Ato_Ini = ano_Ato_Ini;
           this.cbr_Dt_End = cbr_Dt_End;
           this.cbr_Dt_Start = cbr_Dt_Start;
           this.cbr_Id_Tp_Afast = cbr_Id_Tp_Afast;
           this.cbr_N_Tp_Afast = cbr_N_Tp_Afast;
           this.cbr_N_Tp_Remuner = cbr_N_Tp_Remuner;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.numero_Ato_Ini = numero_Ato_Ini;
           this.tipo_Ato = tipo_Ato;
    }


    /**
     * Gets the ano_Ato_Ini value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @return ano_Ato_Ini
     */
    public java.lang.Double getAno_Ato_Ini() {
        return ano_Ato_Ini;
    }


    /**
     * Sets the ano_Ato_Ini value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @param ano_Ato_Ini
     */
    public void setAno_Ato_Ini(java.lang.Double ano_Ato_Ini) {
        this.ano_Ato_Ini = ano_Ato_Ini;
    }


    /**
     * Gets the cbr_Dt_End value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @return cbr_Dt_End
     */
    public java.util.Calendar getCbr_Dt_End() {
        return cbr_Dt_End;
    }


    /**
     * Sets the cbr_Dt_End value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @param cbr_Dt_End
     */
    public void setCbr_Dt_End(java.util.Calendar cbr_Dt_End) {
        this.cbr_Dt_End = cbr_Dt_End;
    }


    /**
     * Gets the cbr_Dt_Start value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @return cbr_Dt_Start
     */
    public java.util.Calendar getCbr_Dt_Start() {
        return cbr_Dt_Start;
    }


    /**
     * Sets the cbr_Dt_Start value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @param cbr_Dt_Start
     */
    public void setCbr_Dt_Start(java.util.Calendar cbr_Dt_Start) {
        this.cbr_Dt_Start = cbr_Dt_Start;
    }


    /**
     * Gets the cbr_Id_Tp_Afast value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @return cbr_Id_Tp_Afast
     */
    public java.lang.Double getCbr_Id_Tp_Afast() {
        return cbr_Id_Tp_Afast;
    }


    /**
     * Sets the cbr_Id_Tp_Afast value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @param cbr_Id_Tp_Afast
     */
    public void setCbr_Id_Tp_Afast(java.lang.Double cbr_Id_Tp_Afast) {
        this.cbr_Id_Tp_Afast = cbr_Id_Tp_Afast;
    }


    /**
     * Gets the cbr_N_Tp_Afast value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @return cbr_N_Tp_Afast
     */
    public java.lang.String getCbr_N_Tp_Afast() {
        return cbr_N_Tp_Afast;
    }


    /**
     * Sets the cbr_N_Tp_Afast value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @param cbr_N_Tp_Afast
     */
    public void setCbr_N_Tp_Afast(java.lang.String cbr_N_Tp_Afast) {
        this.cbr_N_Tp_Afast = cbr_N_Tp_Afast;
    }


    /**
     * Gets the cbr_N_Tp_Remuner value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @return cbr_N_Tp_Remuner
     */
    public java.lang.String getCbr_N_Tp_Remuner() {
        return cbr_N_Tp_Remuner;
    }


    /**
     * Sets the cbr_N_Tp_Remuner value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @param cbr_N_Tp_Remuner
     */
    public void setCbr_N_Tp_Remuner(java.lang.String cbr_N_Tp_Remuner) {
        this.cbr_N_Tp_Remuner = cbr_N_Tp_Remuner;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the numero_Ato_Ini value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @return numero_Ato_Ini
     */
    public java.lang.Double getNumero_Ato_Ini() {
        return numero_Ato_Ini;
    }


    /**
     * Sets the numero_Ato_Ini value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @param numero_Ato_Ini
     */
    public void setNumero_Ato_Ini(java.lang.Double numero_Ato_Ini) {
        this.numero_Ato_Ini = numero_Ato_Ini;
    }


    /**
     * Gets the tipo_Ato value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @return tipo_Ato
     */
    public java.lang.String getTipo_Ato() {
        return tipo_Ato;
    }


    /**
     * Sets the tipo_Ato value for this Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.
     * 
     * @param tipo_Ato
     */
    public void setTipo_Ato(java.lang.String tipo_Ato) {
        this.tipo_Ato = tipo_Ato;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord)) return false;
        Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord other = (Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.ano_Ato_Ini==null && other.getAno_Ato_Ini()==null) || 
             (this.ano_Ato_Ini!=null &&
              this.ano_Ato_Ini.equals(other.getAno_Ato_Ini()))) &&
            ((this.cbr_Dt_End==null && other.getCbr_Dt_End()==null) || 
             (this.cbr_Dt_End!=null &&
              this.cbr_Dt_End.equals(other.getCbr_Dt_End()))) &&
            ((this.cbr_Dt_Start==null && other.getCbr_Dt_Start()==null) || 
             (this.cbr_Dt_Start!=null &&
              this.cbr_Dt_Start.equals(other.getCbr_Dt_Start()))) &&
            ((this.cbr_Id_Tp_Afast==null && other.getCbr_Id_Tp_Afast()==null) || 
             (this.cbr_Id_Tp_Afast!=null &&
              this.cbr_Id_Tp_Afast.equals(other.getCbr_Id_Tp_Afast()))) &&
            ((this.cbr_N_Tp_Afast==null && other.getCbr_N_Tp_Afast()==null) || 
             (this.cbr_N_Tp_Afast!=null &&
              this.cbr_N_Tp_Afast.equals(other.getCbr_N_Tp_Afast()))) &&
            ((this.cbr_N_Tp_Remuner==null && other.getCbr_N_Tp_Remuner()==null) || 
             (this.cbr_N_Tp_Remuner!=null &&
              this.cbr_N_Tp_Remuner.equals(other.getCbr_N_Tp_Remuner()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.numero_Ato_Ini==null && other.getNumero_Ato_Ini()==null) || 
             (this.numero_Ato_Ini!=null &&
              this.numero_Ato_Ini.equals(other.getNumero_Ato_Ini()))) &&
            ((this.tipo_Ato==null && other.getTipo_Ato()==null) || 
             (this.tipo_Ato!=null &&
              this.tipo_Ato.equals(other.getTipo_Ato())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getAno_Ato_Ini() != null) {
            _hashCode += getAno_Ato_Ini().hashCode();
        }
        if (getCbr_Dt_End() != null) {
            _hashCode += getCbr_Dt_End().hashCode();
        }
        if (getCbr_Dt_Start() != null) {
            _hashCode += getCbr_Dt_Start().hashCode();
        }
        if (getCbr_Id_Tp_Afast() != null) {
            _hashCode += getCbr_Id_Tp_Afast().hashCode();
        }
        if (getCbr_N_Tp_Afast() != null) {
            _hashCode += getCbr_N_Tp_Afast().hashCode();
        }
        if (getCbr_N_Tp_Remuner() != null) {
            _hashCode += getCbr_N_Tp_Remuner().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getNumero_Ato_Ini() != null) {
            _hashCode += getNumero_Ato_Ini().hashCode();
        }
        if (getTipo_Ato() != null) {
            _hashCode += getTipo_Ato().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Cbr_Ifc_Ws_Out_Licenca_Sem_VenRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("ano_Ato_Ini");
        elemField.setXmlName(new javax.xml.namespace.QName("", "ano_Ato_Ini"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Dt_End");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Dt_End"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Dt_Start");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Dt_Start"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Id_Tp_Afast");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Id_Tp_Afast"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_N_Tp_Afast");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_N_Tp_Afast"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_N_Tp_Remuner");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_N_Tp_Remuner"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("numero_Ato_Ini");
        elemField.setXmlName(new javax.xml.namespace.QName("", "numero_Ato_Ini"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("tipo_Ato");
        elemField.setXmlName(new javax.xml.namespace.QName("", "tipo_Ato"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
