/**
 * Cbr_Ifc_Ws_Vwpessoa_BancoRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.meta4.schemas.types;

public class Cbr_Ifc_Ws_Vwpessoa_BancoRecord  implements java.io.Serializable {
    private java.lang.String id_Currency;

    private java.lang.String id_Organization;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String sco_Account_Number;

    private java.util.Calendar sco_Dt_End;

    private java.util.Calendar sco_Dt_Start;

    private java.lang.String sco_Entitled;

    private java.lang.String sco_Gb_Bank;

    private java.lang.String sco_Id_Bank_Branch;

    private java.lang.String sco_Id_Banktype;

    private java.lang.String sco_Id_Person;

    private java.lang.Double sco_Or_Account;

    public Cbr_Ifc_Ws_Vwpessoa_BancoRecord() {
    }

    public Cbr_Ifc_Ws_Vwpessoa_BancoRecord(
           java.lang.String id_Currency,
           java.lang.String id_Organization,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String sco_Account_Number,
           java.util.Calendar sco_Dt_End,
           java.util.Calendar sco_Dt_Start,
           java.lang.String sco_Entitled,
           java.lang.String sco_Gb_Bank,
           java.lang.String sco_Id_Bank_Branch,
           java.lang.String sco_Id_Banktype,
           java.lang.String sco_Id_Person,
           java.lang.Double sco_Or_Account) {
           this.id_Currency = id_Currency;
           this.id_Organization = id_Organization;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.sco_Account_Number = sco_Account_Number;
           this.sco_Dt_End = sco_Dt_End;
           this.sco_Dt_Start = sco_Dt_Start;
           this.sco_Entitled = sco_Entitled;
           this.sco_Gb_Bank = sco_Gb_Bank;
           this.sco_Id_Bank_Branch = sco_Id_Bank_Branch;
           this.sco_Id_Banktype = sco_Id_Banktype;
           this.sco_Id_Person = sco_Id_Person;
           this.sco_Or_Account = sco_Or_Account;
    }


    /**
     * Gets the id_Currency value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @return id_Currency
     */
    public java.lang.String getId_Currency() {
        return id_Currency;
    }


    /**
     * Sets the id_Currency value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @param id_Currency
     */
    public void setId_Currency(java.lang.String id_Currency) {
        this.id_Currency = id_Currency;
    }


    /**
     * Gets the id_Organization value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @return id_Organization
     */
    public java.lang.String getId_Organization() {
        return id_Organization;
    }


    /**
     * Sets the id_Organization value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @param id_Organization
     */
    public void setId_Organization(java.lang.String id_Organization) {
        this.id_Organization = id_Organization;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the sco_Account_Number value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @return sco_Account_Number
     */
    public java.lang.String getSco_Account_Number() {
        return sco_Account_Number;
    }


    /**
     * Sets the sco_Account_Number value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @param sco_Account_Number
     */
    public void setSco_Account_Number(java.lang.String sco_Account_Number) {
        this.sco_Account_Number = sco_Account_Number;
    }


    /**
     * Gets the sco_Dt_End value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @return sco_Dt_End
     */
    public java.util.Calendar getSco_Dt_End() {
        return sco_Dt_End;
    }


    /**
     * Sets the sco_Dt_End value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @param sco_Dt_End
     */
    public void setSco_Dt_End(java.util.Calendar sco_Dt_End) {
        this.sco_Dt_End = sco_Dt_End;
    }


    /**
     * Gets the sco_Dt_Start value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @return sco_Dt_Start
     */
    public java.util.Calendar getSco_Dt_Start() {
        return sco_Dt_Start;
    }


    /**
     * Sets the sco_Dt_Start value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @param sco_Dt_Start
     */
    public void setSco_Dt_Start(java.util.Calendar sco_Dt_Start) {
        this.sco_Dt_Start = sco_Dt_Start;
    }


    /**
     * Gets the sco_Entitled value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @return sco_Entitled
     */
    public java.lang.String getSco_Entitled() {
        return sco_Entitled;
    }


    /**
     * Sets the sco_Entitled value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @param sco_Entitled
     */
    public void setSco_Entitled(java.lang.String sco_Entitled) {
        this.sco_Entitled = sco_Entitled;
    }


    /**
     * Gets the sco_Gb_Bank value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @return sco_Gb_Bank
     */
    public java.lang.String getSco_Gb_Bank() {
        return sco_Gb_Bank;
    }


    /**
     * Sets the sco_Gb_Bank value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @param sco_Gb_Bank
     */
    public void setSco_Gb_Bank(java.lang.String sco_Gb_Bank) {
        this.sco_Gb_Bank = sco_Gb_Bank;
    }


    /**
     * Gets the sco_Id_Bank_Branch value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @return sco_Id_Bank_Branch
     */
    public java.lang.String getSco_Id_Bank_Branch() {
        return sco_Id_Bank_Branch;
    }


    /**
     * Sets the sco_Id_Bank_Branch value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @param sco_Id_Bank_Branch
     */
    public void setSco_Id_Bank_Branch(java.lang.String sco_Id_Bank_Branch) {
        this.sco_Id_Bank_Branch = sco_Id_Bank_Branch;
    }


    /**
     * Gets the sco_Id_Banktype value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @return sco_Id_Banktype
     */
    public java.lang.String getSco_Id_Banktype() {
        return sco_Id_Banktype;
    }


    /**
     * Sets the sco_Id_Banktype value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @param sco_Id_Banktype
     */
    public void setSco_Id_Banktype(java.lang.String sco_Id_Banktype) {
        this.sco_Id_Banktype = sco_Id_Banktype;
    }


    /**
     * Gets the sco_Id_Person value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @return sco_Id_Person
     */
    public java.lang.String getSco_Id_Person() {
        return sco_Id_Person;
    }


    /**
     * Sets the sco_Id_Person value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @param sco_Id_Person
     */
    public void setSco_Id_Person(java.lang.String sco_Id_Person) {
        this.sco_Id_Person = sco_Id_Person;
    }


    /**
     * Gets the sco_Or_Account value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @return sco_Or_Account
     */
    public java.lang.Double getSco_Or_Account() {
        return sco_Or_Account;
    }


    /**
     * Sets the sco_Or_Account value for this Cbr_Ifc_Ws_Vwpessoa_BancoRecord.
     * 
     * @param sco_Or_Account
     */
    public void setSco_Or_Account(java.lang.Double sco_Or_Account) {
        this.sco_Or_Account = sco_Or_Account;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Cbr_Ifc_Ws_Vwpessoa_BancoRecord)) return false;
        Cbr_Ifc_Ws_Vwpessoa_BancoRecord other = (Cbr_Ifc_Ws_Vwpessoa_BancoRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.id_Currency==null && other.getId_Currency()==null) || 
             (this.id_Currency!=null &&
              this.id_Currency.equals(other.getId_Currency()))) &&
            ((this.id_Organization==null && other.getId_Organization()==null) || 
             (this.id_Organization!=null &&
              this.id_Organization.equals(other.getId_Organization()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.sco_Account_Number==null && other.getSco_Account_Number()==null) || 
             (this.sco_Account_Number!=null &&
              this.sco_Account_Number.equals(other.getSco_Account_Number()))) &&
            ((this.sco_Dt_End==null && other.getSco_Dt_End()==null) || 
             (this.sco_Dt_End!=null &&
              this.sco_Dt_End.equals(other.getSco_Dt_End()))) &&
            ((this.sco_Dt_Start==null && other.getSco_Dt_Start()==null) || 
             (this.sco_Dt_Start!=null &&
              this.sco_Dt_Start.equals(other.getSco_Dt_Start()))) &&
            ((this.sco_Entitled==null && other.getSco_Entitled()==null) || 
             (this.sco_Entitled!=null &&
              this.sco_Entitled.equals(other.getSco_Entitled()))) &&
            ((this.sco_Gb_Bank==null && other.getSco_Gb_Bank()==null) || 
             (this.sco_Gb_Bank!=null &&
              this.sco_Gb_Bank.equals(other.getSco_Gb_Bank()))) &&
            ((this.sco_Id_Bank_Branch==null && other.getSco_Id_Bank_Branch()==null) || 
             (this.sco_Id_Bank_Branch!=null &&
              this.sco_Id_Bank_Branch.equals(other.getSco_Id_Bank_Branch()))) &&
            ((this.sco_Id_Banktype==null && other.getSco_Id_Banktype()==null) || 
             (this.sco_Id_Banktype!=null &&
              this.sco_Id_Banktype.equals(other.getSco_Id_Banktype()))) &&
            ((this.sco_Id_Person==null && other.getSco_Id_Person()==null) || 
             (this.sco_Id_Person!=null &&
              this.sco_Id_Person.equals(other.getSco_Id_Person()))) &&
            ((this.sco_Or_Account==null && other.getSco_Or_Account()==null) || 
             (this.sco_Or_Account!=null &&
              this.sco_Or_Account.equals(other.getSco_Or_Account())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getId_Currency() != null) {
            _hashCode += getId_Currency().hashCode();
        }
        if (getId_Organization() != null) {
            _hashCode += getId_Organization().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getSco_Account_Number() != null) {
            _hashCode += getSco_Account_Number().hashCode();
        }
        if (getSco_Dt_End() != null) {
            _hashCode += getSco_Dt_End().hashCode();
        }
        if (getSco_Dt_Start() != null) {
            _hashCode += getSco_Dt_Start().hashCode();
        }
        if (getSco_Entitled() != null) {
            _hashCode += getSco_Entitled().hashCode();
        }
        if (getSco_Gb_Bank() != null) {
            _hashCode += getSco_Gb_Bank().hashCode();
        }
        if (getSco_Id_Bank_Branch() != null) {
            _hashCode += getSco_Id_Bank_Branch().hashCode();
        }
        if (getSco_Id_Banktype() != null) {
            _hashCode += getSco_Id_Banktype().hashCode();
        }
        if (getSco_Id_Person() != null) {
            _hashCode += getSco_Id_Person().hashCode();
        }
        if (getSco_Or_Account() != null) {
            _hashCode += getSco_Or_Account().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Cbr_Ifc_Ws_Vwpessoa_BancoRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Cbr_Ifc_Ws_Vwpessoa_BancoRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("id_Currency");
        elemField.setXmlName(new javax.xml.namespace.QName("", "id_Currency"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("id_Organization");
        elemField.setXmlName(new javax.xml.namespace.QName("", "id_Organization"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Account_Number");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Account_Number"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Dt_End");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Dt_End"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Dt_Start");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Dt_Start"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Entitled");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Entitled"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Gb_Bank");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Gb_Bank"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Id_Bank_Branch");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Id_Bank_Branch"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Id_Banktype");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Id_Banktype"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Id_Person");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Id_Person"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Or_Account");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Or_Account"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
