/**
 * Cbr_Ifc_Ws_VwenderecoRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.meta4.schemas.types;

public class Cbr_Ifc_Ws_VwenderecoRecord  implements java.io.Serializable {
    private java.lang.Double cbr_Or_Logradouro;

    private java.lang.String id_Organization;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String sco_Gb_Address;

    private java.lang.String std_Address_Line_1;

    private java.lang.String std_Address_Line_2;

    private java.util.Calendar std_Dt_End;

    private java.util.Calendar std_Dt_Start;

    private java.lang.String std_Id_Country;

    private java.lang.String std_Id_Geo_Div;

    private java.lang.String std_Id_Geo_Place;

    private java.lang.String std_Id_Location_Type;

    private java.lang.String std_Id_Person;

    private java.lang.String std_Id_Sub_Geo_Div;

    private java.lang.String std_Mailing_Check;

    private java.lang.Double std_Or_Address;

    private java.lang.String std_Zip_Code;

    public Cbr_Ifc_Ws_VwenderecoRecord() {
    }

    public Cbr_Ifc_Ws_VwenderecoRecord(
           java.lang.Double cbr_Or_Logradouro,
           java.lang.String id_Organization,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String sco_Gb_Address,
           java.lang.String std_Address_Line_1,
           java.lang.String std_Address_Line_2,
           java.util.Calendar std_Dt_End,
           java.util.Calendar std_Dt_Start,
           java.lang.String std_Id_Country,
           java.lang.String std_Id_Geo_Div,
           java.lang.String std_Id_Geo_Place,
           java.lang.String std_Id_Location_Type,
           java.lang.String std_Id_Person,
           java.lang.String std_Id_Sub_Geo_Div,
           java.lang.String std_Mailing_Check,
           java.lang.Double std_Or_Address,
           java.lang.String std_Zip_Code) {
           this.cbr_Or_Logradouro = cbr_Or_Logradouro;
           this.id_Organization = id_Organization;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.sco_Gb_Address = sco_Gb_Address;
           this.std_Address_Line_1 = std_Address_Line_1;
           this.std_Address_Line_2 = std_Address_Line_2;
           this.std_Dt_End = std_Dt_End;
           this.std_Dt_Start = std_Dt_Start;
           this.std_Id_Country = std_Id_Country;
           this.std_Id_Geo_Div = std_Id_Geo_Div;
           this.std_Id_Geo_Place = std_Id_Geo_Place;
           this.std_Id_Location_Type = std_Id_Location_Type;
           this.std_Id_Person = std_Id_Person;
           this.std_Id_Sub_Geo_Div = std_Id_Sub_Geo_Div;
           this.std_Mailing_Check = std_Mailing_Check;
           this.std_Or_Address = std_Or_Address;
           this.std_Zip_Code = std_Zip_Code;
    }


    /**
     * Gets the cbr_Or_Logradouro value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return cbr_Or_Logradouro
     */
    public java.lang.Double getCbr_Or_Logradouro() {
        return cbr_Or_Logradouro;
    }


    /**
     * Sets the cbr_Or_Logradouro value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param cbr_Or_Logradouro
     */
    public void setCbr_Or_Logradouro(java.lang.Double cbr_Or_Logradouro) {
        this.cbr_Or_Logradouro = cbr_Or_Logradouro;
    }


    /**
     * Gets the id_Organization value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return id_Organization
     */
    public java.lang.String getId_Organization() {
        return id_Organization;
    }


    /**
     * Sets the id_Organization value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param id_Organization
     */
    public void setId_Organization(java.lang.String id_Organization) {
        this.id_Organization = id_Organization;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the sco_Gb_Address value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return sco_Gb_Address
     */
    public java.lang.String getSco_Gb_Address() {
        return sco_Gb_Address;
    }


    /**
     * Sets the sco_Gb_Address value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param sco_Gb_Address
     */
    public void setSco_Gb_Address(java.lang.String sco_Gb_Address) {
        this.sco_Gb_Address = sco_Gb_Address;
    }


    /**
     * Gets the std_Address_Line_1 value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return std_Address_Line_1
     */
    public java.lang.String getStd_Address_Line_1() {
        return std_Address_Line_1;
    }


    /**
     * Sets the std_Address_Line_1 value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param std_Address_Line_1
     */
    public void setStd_Address_Line_1(java.lang.String std_Address_Line_1) {
        this.std_Address_Line_1 = std_Address_Line_1;
    }


    /**
     * Gets the std_Address_Line_2 value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return std_Address_Line_2
     */
    public java.lang.String getStd_Address_Line_2() {
        return std_Address_Line_2;
    }


    /**
     * Sets the std_Address_Line_2 value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param std_Address_Line_2
     */
    public void setStd_Address_Line_2(java.lang.String std_Address_Line_2) {
        this.std_Address_Line_2 = std_Address_Line_2;
    }


    /**
     * Gets the std_Dt_End value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return std_Dt_End
     */
    public java.util.Calendar getStd_Dt_End() {
        return std_Dt_End;
    }


    /**
     * Sets the std_Dt_End value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param std_Dt_End
     */
    public void setStd_Dt_End(java.util.Calendar std_Dt_End) {
        this.std_Dt_End = std_Dt_End;
    }


    /**
     * Gets the std_Dt_Start value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return std_Dt_Start
     */
    public java.util.Calendar getStd_Dt_Start() {
        return std_Dt_Start;
    }


    /**
     * Sets the std_Dt_Start value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param std_Dt_Start
     */
    public void setStd_Dt_Start(java.util.Calendar std_Dt_Start) {
        this.std_Dt_Start = std_Dt_Start;
    }


    /**
     * Gets the std_Id_Country value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return std_Id_Country
     */
    public java.lang.String getStd_Id_Country() {
        return std_Id_Country;
    }


    /**
     * Sets the std_Id_Country value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param std_Id_Country
     */
    public void setStd_Id_Country(java.lang.String std_Id_Country) {
        this.std_Id_Country = std_Id_Country;
    }


    /**
     * Gets the std_Id_Geo_Div value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return std_Id_Geo_Div
     */
    public java.lang.String getStd_Id_Geo_Div() {
        return std_Id_Geo_Div;
    }


    /**
     * Sets the std_Id_Geo_Div value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param std_Id_Geo_Div
     */
    public void setStd_Id_Geo_Div(java.lang.String std_Id_Geo_Div) {
        this.std_Id_Geo_Div = std_Id_Geo_Div;
    }


    /**
     * Gets the std_Id_Geo_Place value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return std_Id_Geo_Place
     */
    public java.lang.String getStd_Id_Geo_Place() {
        return std_Id_Geo_Place;
    }


    /**
     * Sets the std_Id_Geo_Place value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param std_Id_Geo_Place
     */
    public void setStd_Id_Geo_Place(java.lang.String std_Id_Geo_Place) {
        this.std_Id_Geo_Place = std_Id_Geo_Place;
    }


    /**
     * Gets the std_Id_Location_Type value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return std_Id_Location_Type
     */
    public java.lang.String getStd_Id_Location_Type() {
        return std_Id_Location_Type;
    }


    /**
     * Sets the std_Id_Location_Type value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param std_Id_Location_Type
     */
    public void setStd_Id_Location_Type(java.lang.String std_Id_Location_Type) {
        this.std_Id_Location_Type = std_Id_Location_Type;
    }


    /**
     * Gets the std_Id_Person value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return std_Id_Person
     */
    public java.lang.String getStd_Id_Person() {
        return std_Id_Person;
    }


    /**
     * Sets the std_Id_Person value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param std_Id_Person
     */
    public void setStd_Id_Person(java.lang.String std_Id_Person) {
        this.std_Id_Person = std_Id_Person;
    }


    /**
     * Gets the std_Id_Sub_Geo_Div value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return std_Id_Sub_Geo_Div
     */
    public java.lang.String getStd_Id_Sub_Geo_Div() {
        return std_Id_Sub_Geo_Div;
    }


    /**
     * Sets the std_Id_Sub_Geo_Div value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param std_Id_Sub_Geo_Div
     */
    public void setStd_Id_Sub_Geo_Div(java.lang.String std_Id_Sub_Geo_Div) {
        this.std_Id_Sub_Geo_Div = std_Id_Sub_Geo_Div;
    }


    /**
     * Gets the std_Mailing_Check value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return std_Mailing_Check
     */
    public java.lang.String getStd_Mailing_Check() {
        return std_Mailing_Check;
    }


    /**
     * Sets the std_Mailing_Check value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param std_Mailing_Check
     */
    public void setStd_Mailing_Check(java.lang.String std_Mailing_Check) {
        this.std_Mailing_Check = std_Mailing_Check;
    }


    /**
     * Gets the std_Or_Address value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return std_Or_Address
     */
    public java.lang.Double getStd_Or_Address() {
        return std_Or_Address;
    }


    /**
     * Sets the std_Or_Address value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param std_Or_Address
     */
    public void setStd_Or_Address(java.lang.Double std_Or_Address) {
        this.std_Or_Address = std_Or_Address;
    }


    /**
     * Gets the std_Zip_Code value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @return std_Zip_Code
     */
    public java.lang.String getStd_Zip_Code() {
        return std_Zip_Code;
    }


    /**
     * Sets the std_Zip_Code value for this Cbr_Ifc_Ws_VwenderecoRecord.
     * 
     * @param std_Zip_Code
     */
    public void setStd_Zip_Code(java.lang.String std_Zip_Code) {
        this.std_Zip_Code = std_Zip_Code;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Cbr_Ifc_Ws_VwenderecoRecord)) return false;
        Cbr_Ifc_Ws_VwenderecoRecord other = (Cbr_Ifc_Ws_VwenderecoRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.cbr_Or_Logradouro==null && other.getCbr_Or_Logradouro()==null) || 
             (this.cbr_Or_Logradouro!=null &&
              this.cbr_Or_Logradouro.equals(other.getCbr_Or_Logradouro()))) &&
            ((this.id_Organization==null && other.getId_Organization()==null) || 
             (this.id_Organization!=null &&
              this.id_Organization.equals(other.getId_Organization()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.sco_Gb_Address==null && other.getSco_Gb_Address()==null) || 
             (this.sco_Gb_Address!=null &&
              this.sco_Gb_Address.equals(other.getSco_Gb_Address()))) &&
            ((this.std_Address_Line_1==null && other.getStd_Address_Line_1()==null) || 
             (this.std_Address_Line_1!=null &&
              this.std_Address_Line_1.equals(other.getStd_Address_Line_1()))) &&
            ((this.std_Address_Line_2==null && other.getStd_Address_Line_2()==null) || 
             (this.std_Address_Line_2!=null &&
              this.std_Address_Line_2.equals(other.getStd_Address_Line_2()))) &&
            ((this.std_Dt_End==null && other.getStd_Dt_End()==null) || 
             (this.std_Dt_End!=null &&
              this.std_Dt_End.equals(other.getStd_Dt_End()))) &&
            ((this.std_Dt_Start==null && other.getStd_Dt_Start()==null) || 
             (this.std_Dt_Start!=null &&
              this.std_Dt_Start.equals(other.getStd_Dt_Start()))) &&
            ((this.std_Id_Country==null && other.getStd_Id_Country()==null) || 
             (this.std_Id_Country!=null &&
              this.std_Id_Country.equals(other.getStd_Id_Country()))) &&
            ((this.std_Id_Geo_Div==null && other.getStd_Id_Geo_Div()==null) || 
             (this.std_Id_Geo_Div!=null &&
              this.std_Id_Geo_Div.equals(other.getStd_Id_Geo_Div()))) &&
            ((this.std_Id_Geo_Place==null && other.getStd_Id_Geo_Place()==null) || 
             (this.std_Id_Geo_Place!=null &&
              this.std_Id_Geo_Place.equals(other.getStd_Id_Geo_Place()))) &&
            ((this.std_Id_Location_Type==null && other.getStd_Id_Location_Type()==null) || 
             (this.std_Id_Location_Type!=null &&
              this.std_Id_Location_Type.equals(other.getStd_Id_Location_Type()))) &&
            ((this.std_Id_Person==null && other.getStd_Id_Person()==null) || 
             (this.std_Id_Person!=null &&
              this.std_Id_Person.equals(other.getStd_Id_Person()))) &&
            ((this.std_Id_Sub_Geo_Div==null && other.getStd_Id_Sub_Geo_Div()==null) || 
             (this.std_Id_Sub_Geo_Div!=null &&
              this.std_Id_Sub_Geo_Div.equals(other.getStd_Id_Sub_Geo_Div()))) &&
            ((this.std_Mailing_Check==null && other.getStd_Mailing_Check()==null) || 
             (this.std_Mailing_Check!=null &&
              this.std_Mailing_Check.equals(other.getStd_Mailing_Check()))) &&
            ((this.std_Or_Address==null && other.getStd_Or_Address()==null) || 
             (this.std_Or_Address!=null &&
              this.std_Or_Address.equals(other.getStd_Or_Address()))) &&
            ((this.std_Zip_Code==null && other.getStd_Zip_Code()==null) || 
             (this.std_Zip_Code!=null &&
              this.std_Zip_Code.equals(other.getStd_Zip_Code())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCbr_Or_Logradouro() != null) {
            _hashCode += getCbr_Or_Logradouro().hashCode();
        }
        if (getId_Organization() != null) {
            _hashCode += getId_Organization().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getSco_Gb_Address() != null) {
            _hashCode += getSco_Gb_Address().hashCode();
        }
        if (getStd_Address_Line_1() != null) {
            _hashCode += getStd_Address_Line_1().hashCode();
        }
        if (getStd_Address_Line_2() != null) {
            _hashCode += getStd_Address_Line_2().hashCode();
        }
        if (getStd_Dt_End() != null) {
            _hashCode += getStd_Dt_End().hashCode();
        }
        if (getStd_Dt_Start() != null) {
            _hashCode += getStd_Dt_Start().hashCode();
        }
        if (getStd_Id_Country() != null) {
            _hashCode += getStd_Id_Country().hashCode();
        }
        if (getStd_Id_Geo_Div() != null) {
            _hashCode += getStd_Id_Geo_Div().hashCode();
        }
        if (getStd_Id_Geo_Place() != null) {
            _hashCode += getStd_Id_Geo_Place().hashCode();
        }
        if (getStd_Id_Location_Type() != null) {
            _hashCode += getStd_Id_Location_Type().hashCode();
        }
        if (getStd_Id_Person() != null) {
            _hashCode += getStd_Id_Person().hashCode();
        }
        if (getStd_Id_Sub_Geo_Div() != null) {
            _hashCode += getStd_Id_Sub_Geo_Div().hashCode();
        }
        if (getStd_Mailing_Check() != null) {
            _hashCode += getStd_Mailing_Check().hashCode();
        }
        if (getStd_Or_Address() != null) {
            _hashCode += getStd_Or_Address().hashCode();
        }
        if (getStd_Zip_Code() != null) {
            _hashCode += getStd_Zip_Code().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Cbr_Ifc_Ws_VwenderecoRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Cbr_Ifc_Ws_VwenderecoRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Or_Logradouro");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Or_Logradouro"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("id_Organization");
        elemField.setXmlName(new javax.xml.namespace.QName("", "id_Organization"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Gb_Address");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Gb_Address"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Address_Line_1");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Address_Line_1"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Address_Line_2");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Address_Line_2"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Dt_End");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Dt_End"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Dt_Start");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Dt_Start"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Country");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Country"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Geo_Div");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Geo_Div"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Geo_Place");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Geo_Place"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Location_Type");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Location_Type"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Person");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Person"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Sub_Geo_Div");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Sub_Geo_Div"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Mailing_Check");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Mailing_Check"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Or_Address");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Or_Address"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Zip_Code");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Zip_Code"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
