/**
 * Cbr_Pesquisar_Agencia_BancariaRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.meta4.schemas.types;

public class Cbr_Pesquisar_Agencia_BancariaRecord  implements java.io.Serializable {
    private java.lang.String cbr_Id_Banco;

    private java.lang.String cbr_N_Banco;

    private java.lang.String cbr_N_Bank_Branch;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String sco_Chips_Id;

    private java.lang.String sco_Comment;

    private java.util.Calendar sco_Dt_End;

    private java.util.Calendar sco_Dt_Start;

    private java.lang.String sco_Id_Bank_Branch;

    public Cbr_Pesquisar_Agencia_BancariaRecord() {
    }

    public Cbr_Pesquisar_Agencia_BancariaRecord(
           java.lang.String cbr_Id_Banco,
           java.lang.String cbr_N_Banco,
           java.lang.String cbr_N_Bank_Branch,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String sco_Chips_Id,
           java.lang.String sco_Comment,
           java.util.Calendar sco_Dt_End,
           java.util.Calendar sco_Dt_Start,
           java.lang.String sco_Id_Bank_Branch) {
           this.cbr_Id_Banco = cbr_Id_Banco;
           this.cbr_N_Banco = cbr_N_Banco;
           this.cbr_N_Bank_Branch = cbr_N_Bank_Branch;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.sco_Chips_Id = sco_Chips_Id;
           this.sco_Comment = sco_Comment;
           this.sco_Dt_End = sco_Dt_End;
           this.sco_Dt_Start = sco_Dt_Start;
           this.sco_Id_Bank_Branch = sco_Id_Bank_Branch;
    }


    /**
     * Gets the cbr_Id_Banco value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @return cbr_Id_Banco
     */
    public java.lang.String getCbr_Id_Banco() {
        return cbr_Id_Banco;
    }


    /**
     * Sets the cbr_Id_Banco value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @param cbr_Id_Banco
     */
    public void setCbr_Id_Banco(java.lang.String cbr_Id_Banco) {
        this.cbr_Id_Banco = cbr_Id_Banco;
    }


    /**
     * Gets the cbr_N_Banco value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @return cbr_N_Banco
     */
    public java.lang.String getCbr_N_Banco() {
        return cbr_N_Banco;
    }


    /**
     * Sets the cbr_N_Banco value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @param cbr_N_Banco
     */
    public void setCbr_N_Banco(java.lang.String cbr_N_Banco) {
        this.cbr_N_Banco = cbr_N_Banco;
    }


    /**
     * Gets the cbr_N_Bank_Branch value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @return cbr_N_Bank_Branch
     */
    public java.lang.String getCbr_N_Bank_Branch() {
        return cbr_N_Bank_Branch;
    }


    /**
     * Sets the cbr_N_Bank_Branch value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @param cbr_N_Bank_Branch
     */
    public void setCbr_N_Bank_Branch(java.lang.String cbr_N_Bank_Branch) {
        this.cbr_N_Bank_Branch = cbr_N_Bank_Branch;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the sco_Chips_Id value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @return sco_Chips_Id
     */
    public java.lang.String getSco_Chips_Id() {
        return sco_Chips_Id;
    }


    /**
     * Sets the sco_Chips_Id value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @param sco_Chips_Id
     */
    public void setSco_Chips_Id(java.lang.String sco_Chips_Id) {
        this.sco_Chips_Id = sco_Chips_Id;
    }


    /**
     * Gets the sco_Comment value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @return sco_Comment
     */
    public java.lang.String getSco_Comment() {
        return sco_Comment;
    }


    /**
     * Sets the sco_Comment value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @param sco_Comment
     */
    public void setSco_Comment(java.lang.String sco_Comment) {
        this.sco_Comment = sco_Comment;
    }


    /**
     * Gets the sco_Dt_End value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @return sco_Dt_End
     */
    public java.util.Calendar getSco_Dt_End() {
        return sco_Dt_End;
    }


    /**
     * Sets the sco_Dt_End value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @param sco_Dt_End
     */
    public void setSco_Dt_End(java.util.Calendar sco_Dt_End) {
        this.sco_Dt_End = sco_Dt_End;
    }


    /**
     * Gets the sco_Dt_Start value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @return sco_Dt_Start
     */
    public java.util.Calendar getSco_Dt_Start() {
        return sco_Dt_Start;
    }


    /**
     * Sets the sco_Dt_Start value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @param sco_Dt_Start
     */
    public void setSco_Dt_Start(java.util.Calendar sco_Dt_Start) {
        this.sco_Dt_Start = sco_Dt_Start;
    }


    /**
     * Gets the sco_Id_Bank_Branch value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @return sco_Id_Bank_Branch
     */
    public java.lang.String getSco_Id_Bank_Branch() {
        return sco_Id_Bank_Branch;
    }


    /**
     * Sets the sco_Id_Bank_Branch value for this Cbr_Pesquisar_Agencia_BancariaRecord.
     * 
     * @param sco_Id_Bank_Branch
     */
    public void setSco_Id_Bank_Branch(java.lang.String sco_Id_Bank_Branch) {
        this.sco_Id_Bank_Branch = sco_Id_Bank_Branch;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Cbr_Pesquisar_Agencia_BancariaRecord)) return false;
        Cbr_Pesquisar_Agencia_BancariaRecord other = (Cbr_Pesquisar_Agencia_BancariaRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.cbr_Id_Banco==null && other.getCbr_Id_Banco()==null) || 
             (this.cbr_Id_Banco!=null &&
              this.cbr_Id_Banco.equals(other.getCbr_Id_Banco()))) &&
            ((this.cbr_N_Banco==null && other.getCbr_N_Banco()==null) || 
             (this.cbr_N_Banco!=null &&
              this.cbr_N_Banco.equals(other.getCbr_N_Banco()))) &&
            ((this.cbr_N_Bank_Branch==null && other.getCbr_N_Bank_Branch()==null) || 
             (this.cbr_N_Bank_Branch!=null &&
              this.cbr_N_Bank_Branch.equals(other.getCbr_N_Bank_Branch()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.sco_Chips_Id==null && other.getSco_Chips_Id()==null) || 
             (this.sco_Chips_Id!=null &&
              this.sco_Chips_Id.equals(other.getSco_Chips_Id()))) &&
            ((this.sco_Comment==null && other.getSco_Comment()==null) || 
             (this.sco_Comment!=null &&
              this.sco_Comment.equals(other.getSco_Comment()))) &&
            ((this.sco_Dt_End==null && other.getSco_Dt_End()==null) || 
             (this.sco_Dt_End!=null &&
              this.sco_Dt_End.equals(other.getSco_Dt_End()))) &&
            ((this.sco_Dt_Start==null && other.getSco_Dt_Start()==null) || 
             (this.sco_Dt_Start!=null &&
              this.sco_Dt_Start.equals(other.getSco_Dt_Start()))) &&
            ((this.sco_Id_Bank_Branch==null && other.getSco_Id_Bank_Branch()==null) || 
             (this.sco_Id_Bank_Branch!=null &&
              this.sco_Id_Bank_Branch.equals(other.getSco_Id_Bank_Branch())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCbr_Id_Banco() != null) {
            _hashCode += getCbr_Id_Banco().hashCode();
        }
        if (getCbr_N_Banco() != null) {
            _hashCode += getCbr_N_Banco().hashCode();
        }
        if (getCbr_N_Bank_Branch() != null) {
            _hashCode += getCbr_N_Bank_Branch().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getSco_Chips_Id() != null) {
            _hashCode += getSco_Chips_Id().hashCode();
        }
        if (getSco_Comment() != null) {
            _hashCode += getSco_Comment().hashCode();
        }
        if (getSco_Dt_End() != null) {
            _hashCode += getSco_Dt_End().hashCode();
        }
        if (getSco_Dt_Start() != null) {
            _hashCode += getSco_Dt_Start().hashCode();
        }
        if (getSco_Id_Bank_Branch() != null) {
            _hashCode += getSco_Id_Bank_Branch().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Cbr_Pesquisar_Agencia_BancariaRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Cbr_Pesquisar_Agencia_BancariaRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Id_Banco");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Id_Banco"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_N_Banco");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_N_Banco"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_N_Bank_Branch");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_N_Bank_Branch"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Chips_Id");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Chips_Id"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Comment");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Comment"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Dt_End");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Dt_End"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Dt_Start");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Dt_Start"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Id_Bank_Branch");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Id_Bank_Branch"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
