/**
 * Cbr_Estado_CivilRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.meta4.schemas.types;

public class Cbr_Estado_CivilRecord  implements java.io.Serializable {
    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.util.Calendar std_Dt_End;

    private java.util.Calendar std_Dt_Start;

    private java.lang.String std_Id_Hr;

    private java.lang.String std_Id_Marital_Stat;

    public Cbr_Estado_CivilRecord() {
    }

    public Cbr_Estado_CivilRecord(
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.util.Calendar std_Dt_End,
           java.util.Calendar std_Dt_Start,
           java.lang.String std_Id_Hr,
           java.lang.String std_Id_Marital_Stat) {
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.std_Dt_End = std_Dt_End;
           this.std_Dt_Start = std_Dt_Start;
           this.std_Id_Hr = std_Id_Hr;
           this.std_Id_Marital_Stat = std_Id_Marital_Stat;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Cbr_Estado_CivilRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Cbr_Estado_CivilRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Cbr_Estado_CivilRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Cbr_Estado_CivilRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the std_Dt_End value for this Cbr_Estado_CivilRecord.
     * 
     * @return std_Dt_End
     */
    public java.util.Calendar getStd_Dt_End() {
        return std_Dt_End;
    }


    /**
     * Sets the std_Dt_End value for this Cbr_Estado_CivilRecord.
     * 
     * @param std_Dt_End
     */
    public void setStd_Dt_End(java.util.Calendar std_Dt_End) {
        this.std_Dt_End = std_Dt_End;
    }


    /**
     * Gets the std_Dt_Start value for this Cbr_Estado_CivilRecord.
     * 
     * @return std_Dt_Start
     */
    public java.util.Calendar getStd_Dt_Start() {
        return std_Dt_Start;
    }


    /**
     * Sets the std_Dt_Start value for this Cbr_Estado_CivilRecord.
     * 
     * @param std_Dt_Start
     */
    public void setStd_Dt_Start(java.util.Calendar std_Dt_Start) {
        this.std_Dt_Start = std_Dt_Start;
    }


    /**
     * Gets the std_Id_Hr value for this Cbr_Estado_CivilRecord.
     * 
     * @return std_Id_Hr
     */
    public java.lang.String getStd_Id_Hr() {
        return std_Id_Hr;
    }


    /**
     * Sets the std_Id_Hr value for this Cbr_Estado_CivilRecord.
     * 
     * @param std_Id_Hr
     */
    public void setStd_Id_Hr(java.lang.String std_Id_Hr) {
        this.std_Id_Hr = std_Id_Hr;
    }


    /**
     * Gets the std_Id_Marital_Stat value for this Cbr_Estado_CivilRecord.
     * 
     * @return std_Id_Marital_Stat
     */
    public java.lang.String getStd_Id_Marital_Stat() {
        return std_Id_Marital_Stat;
    }


    /**
     * Sets the std_Id_Marital_Stat value for this Cbr_Estado_CivilRecord.
     * 
     * @param std_Id_Marital_Stat
     */
    public void setStd_Id_Marital_Stat(java.lang.String std_Id_Marital_Stat) {
        this.std_Id_Marital_Stat = std_Id_Marital_Stat;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Cbr_Estado_CivilRecord)) return false;
        Cbr_Estado_CivilRecord other = (Cbr_Estado_CivilRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.std_Dt_End==null && other.getStd_Dt_End()==null) || 
             (this.std_Dt_End!=null &&
              this.std_Dt_End.equals(other.getStd_Dt_End()))) &&
            ((this.std_Dt_Start==null && other.getStd_Dt_Start()==null) || 
             (this.std_Dt_Start!=null &&
              this.std_Dt_Start.equals(other.getStd_Dt_Start()))) &&
            ((this.std_Id_Hr==null && other.getStd_Id_Hr()==null) || 
             (this.std_Id_Hr!=null &&
              this.std_Id_Hr.equals(other.getStd_Id_Hr()))) &&
            ((this.std_Id_Marital_Stat==null && other.getStd_Id_Marital_Stat()==null) || 
             (this.std_Id_Marital_Stat!=null &&
              this.std_Id_Marital_Stat.equals(other.getStd_Id_Marital_Stat())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getStd_Dt_End() != null) {
            _hashCode += getStd_Dt_End().hashCode();
        }
        if (getStd_Dt_Start() != null) {
            _hashCode += getStd_Dt_Start().hashCode();
        }
        if (getStd_Id_Hr() != null) {
            _hashCode += getStd_Id_Hr().hashCode();
        }
        if (getStd_Id_Marital_Stat() != null) {
            _hashCode += getStd_Id_Marital_Stat().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Cbr_Estado_CivilRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Cbr_Estado_CivilRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Dt_End");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Dt_End"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Dt_Start");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Dt_Start"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Hr");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Hr"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Marital_Stat");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Marital_Stat"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
