/**
 * Cbr_Pesquisar_LogradouroRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.meta4.schemas.types;

public class Cbr_Pesquisar_LogradouroRecord  implements java.io.Serializable {
    private java.lang.String bairro_Desc;

    private java.lang.String bairro_Id;

    private java.lang.String cep;

    private java.lang.String cidade_Desc;

    private java.lang.String cidade_Id;

    private java.lang.String logr_Desc;

    private java.lang.String logr_Id;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String pais_Desc;

    private java.lang.String pais_Id;

    private java.lang.String tipo_Logr_Desc;

    private java.lang.String tipo_Logr_Id;

    private java.lang.String uf_Desc;

    private java.lang.String uf_Id;

    public Cbr_Pesquisar_LogradouroRecord() {
    }

    public Cbr_Pesquisar_LogradouroRecord(
           java.lang.String bairro_Desc,
           java.lang.String bairro_Id,
           java.lang.String cep,
           java.lang.String cidade_Desc,
           java.lang.String cidade_Id,
           java.lang.String logr_Desc,
           java.lang.String logr_Id,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String pais_Desc,
           java.lang.String pais_Id,
           java.lang.String tipo_Logr_Desc,
           java.lang.String tipo_Logr_Id,
           java.lang.String uf_Desc,
           java.lang.String uf_Id) {
           this.bairro_Desc = bairro_Desc;
           this.bairro_Id = bairro_Id;
           this.cep = cep;
           this.cidade_Desc = cidade_Desc;
           this.cidade_Id = cidade_Id;
           this.logr_Desc = logr_Desc;
           this.logr_Id = logr_Id;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.pais_Desc = pais_Desc;
           this.pais_Id = pais_Id;
           this.tipo_Logr_Desc = tipo_Logr_Desc;
           this.tipo_Logr_Id = tipo_Logr_Id;
           this.uf_Desc = uf_Desc;
           this.uf_Id = uf_Id;
    }


    /**
     * Gets the bairro_Desc value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return bairro_Desc
     */
    public java.lang.String getBairro_Desc() {
        return bairro_Desc;
    }


    /**
     * Sets the bairro_Desc value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param bairro_Desc
     */
    public void setBairro_Desc(java.lang.String bairro_Desc) {
        this.bairro_Desc = bairro_Desc;
    }


    /**
     * Gets the bairro_Id value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return bairro_Id
     */
    public java.lang.String getBairro_Id() {
        return bairro_Id;
    }


    /**
     * Sets the bairro_Id value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param bairro_Id
     */
    public void setBairro_Id(java.lang.String bairro_Id) {
        this.bairro_Id = bairro_Id;
    }


    /**
     * Gets the cep value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return cep
     */
    public java.lang.String getCep() {
        return cep;
    }


    /**
     * Sets the cep value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param cep
     */
    public void setCep(java.lang.String cep) {
        this.cep = cep;
    }


    /**
     * Gets the cidade_Desc value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return cidade_Desc
     */
    public java.lang.String getCidade_Desc() {
        return cidade_Desc;
    }


    /**
     * Sets the cidade_Desc value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param cidade_Desc
     */
    public void setCidade_Desc(java.lang.String cidade_Desc) {
        this.cidade_Desc = cidade_Desc;
    }


    /**
     * Gets the cidade_Id value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return cidade_Id
     */
    public java.lang.String getCidade_Id() {
        return cidade_Id;
    }


    /**
     * Sets the cidade_Id value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param cidade_Id
     */
    public void setCidade_Id(java.lang.String cidade_Id) {
        this.cidade_Id = cidade_Id;
    }


    /**
     * Gets the logr_Desc value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return logr_Desc
     */
    public java.lang.String getLogr_Desc() {
        return logr_Desc;
    }


    /**
     * Sets the logr_Desc value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param logr_Desc
     */
    public void setLogr_Desc(java.lang.String logr_Desc) {
        this.logr_Desc = logr_Desc;
    }


    /**
     * Gets the logr_Id value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return logr_Id
     */
    public java.lang.String getLogr_Id() {
        return logr_Id;
    }


    /**
     * Sets the logr_Id value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param logr_Id
     */
    public void setLogr_Id(java.lang.String logr_Id) {
        this.logr_Id = logr_Id;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the pais_Desc value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return pais_Desc
     */
    public java.lang.String getPais_Desc() {
        return pais_Desc;
    }


    /**
     * Sets the pais_Desc value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param pais_Desc
     */
    public void setPais_Desc(java.lang.String pais_Desc) {
        this.pais_Desc = pais_Desc;
    }


    /**
     * Gets the pais_Id value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return pais_Id
     */
    public java.lang.String getPais_Id() {
        return pais_Id;
    }


    /**
     * Sets the pais_Id value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param pais_Id
     */
    public void setPais_Id(java.lang.String pais_Id) {
        this.pais_Id = pais_Id;
    }


    /**
     * Gets the tipo_Logr_Desc value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return tipo_Logr_Desc
     */
    public java.lang.String getTipo_Logr_Desc() {
        return tipo_Logr_Desc;
    }


    /**
     * Sets the tipo_Logr_Desc value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param tipo_Logr_Desc
     */
    public void setTipo_Logr_Desc(java.lang.String tipo_Logr_Desc) {
        this.tipo_Logr_Desc = tipo_Logr_Desc;
    }


    /**
     * Gets the tipo_Logr_Id value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return tipo_Logr_Id
     */
    public java.lang.String getTipo_Logr_Id() {
        return tipo_Logr_Id;
    }


    /**
     * Sets the tipo_Logr_Id value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param tipo_Logr_Id
     */
    public void setTipo_Logr_Id(java.lang.String tipo_Logr_Id) {
        this.tipo_Logr_Id = tipo_Logr_Id;
    }


    /**
     * Gets the uf_Desc value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return uf_Desc
     */
    public java.lang.String getUf_Desc() {
        return uf_Desc;
    }


    /**
     * Sets the uf_Desc value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param uf_Desc
     */
    public void setUf_Desc(java.lang.String uf_Desc) {
        this.uf_Desc = uf_Desc;
    }


    /**
     * Gets the uf_Id value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @return uf_Id
     */
    public java.lang.String getUf_Id() {
        return uf_Id;
    }


    /**
     * Sets the uf_Id value for this Cbr_Pesquisar_LogradouroRecord.
     * 
     * @param uf_Id
     */
    public void setUf_Id(java.lang.String uf_Id) {
        this.uf_Id = uf_Id;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Cbr_Pesquisar_LogradouroRecord)) return false;
        Cbr_Pesquisar_LogradouroRecord other = (Cbr_Pesquisar_LogradouroRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.bairro_Desc==null && other.getBairro_Desc()==null) || 
             (this.bairro_Desc!=null &&
              this.bairro_Desc.equals(other.getBairro_Desc()))) &&
            ((this.bairro_Id==null && other.getBairro_Id()==null) || 
             (this.bairro_Id!=null &&
              this.bairro_Id.equals(other.getBairro_Id()))) &&
            ((this.cep==null && other.getCep()==null) || 
             (this.cep!=null &&
              this.cep.equals(other.getCep()))) &&
            ((this.cidade_Desc==null && other.getCidade_Desc()==null) || 
             (this.cidade_Desc!=null &&
              this.cidade_Desc.equals(other.getCidade_Desc()))) &&
            ((this.cidade_Id==null && other.getCidade_Id()==null) || 
             (this.cidade_Id!=null &&
              this.cidade_Id.equals(other.getCidade_Id()))) &&
            ((this.logr_Desc==null && other.getLogr_Desc()==null) || 
             (this.logr_Desc!=null &&
              this.logr_Desc.equals(other.getLogr_Desc()))) &&
            ((this.logr_Id==null && other.getLogr_Id()==null) || 
             (this.logr_Id!=null &&
              this.logr_Id.equals(other.getLogr_Id()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.pais_Desc==null && other.getPais_Desc()==null) || 
             (this.pais_Desc!=null &&
              this.pais_Desc.equals(other.getPais_Desc()))) &&
            ((this.pais_Id==null && other.getPais_Id()==null) || 
             (this.pais_Id!=null &&
              this.pais_Id.equals(other.getPais_Id()))) &&
            ((this.tipo_Logr_Desc==null && other.getTipo_Logr_Desc()==null) || 
             (this.tipo_Logr_Desc!=null &&
              this.tipo_Logr_Desc.equals(other.getTipo_Logr_Desc()))) &&
            ((this.tipo_Logr_Id==null && other.getTipo_Logr_Id()==null) || 
             (this.tipo_Logr_Id!=null &&
              this.tipo_Logr_Id.equals(other.getTipo_Logr_Id()))) &&
            ((this.uf_Desc==null && other.getUf_Desc()==null) || 
             (this.uf_Desc!=null &&
              this.uf_Desc.equals(other.getUf_Desc()))) &&
            ((this.uf_Id==null && other.getUf_Id()==null) || 
             (this.uf_Id!=null &&
              this.uf_Id.equals(other.getUf_Id())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getBairro_Desc() != null) {
            _hashCode += getBairro_Desc().hashCode();
        }
        if (getBairro_Id() != null) {
            _hashCode += getBairro_Id().hashCode();
        }
        if (getCep() != null) {
            _hashCode += getCep().hashCode();
        }
        if (getCidade_Desc() != null) {
            _hashCode += getCidade_Desc().hashCode();
        }
        if (getCidade_Id() != null) {
            _hashCode += getCidade_Id().hashCode();
        }
        if (getLogr_Desc() != null) {
            _hashCode += getLogr_Desc().hashCode();
        }
        if (getLogr_Id() != null) {
            _hashCode += getLogr_Id().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getPais_Desc() != null) {
            _hashCode += getPais_Desc().hashCode();
        }
        if (getPais_Id() != null) {
            _hashCode += getPais_Id().hashCode();
        }
        if (getTipo_Logr_Desc() != null) {
            _hashCode += getTipo_Logr_Desc().hashCode();
        }
        if (getTipo_Logr_Id() != null) {
            _hashCode += getTipo_Logr_Id().hashCode();
        }
        if (getUf_Desc() != null) {
            _hashCode += getUf_Desc().hashCode();
        }
        if (getUf_Id() != null) {
            _hashCode += getUf_Id().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Cbr_Pesquisar_LogradouroRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Cbr_Pesquisar_LogradouroRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("bairro_Desc");
        elemField.setXmlName(new javax.xml.namespace.QName("", "bairro_Desc"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("bairro_Id");
        elemField.setXmlName(new javax.xml.namespace.QName("", "bairro_Id"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cep");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cep"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cidade_Desc");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cidade_Desc"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cidade_Id");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cidade_Id"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("logr_Desc");
        elemField.setXmlName(new javax.xml.namespace.QName("", "logr_Desc"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("logr_Id");
        elemField.setXmlName(new javax.xml.namespace.QName("", "logr_Id"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("pais_Desc");
        elemField.setXmlName(new javax.xml.namespace.QName("", "pais_Desc"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("pais_Id");
        elemField.setXmlName(new javax.xml.namespace.QName("", "pais_Id"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("tipo_Logr_Desc");
        elemField.setXmlName(new javax.xml.namespace.QName("", "tipo_Logr_Desc"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("tipo_Logr_Id");
        elemField.setXmlName(new javax.xml.namespace.QName("", "tipo_Logr_Id"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("uf_Desc");
        elemField.setXmlName(new javax.xml.namespace.QName("", "uf_Desc"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("uf_Id");
        elemField.setXmlName(new javax.xml.namespace.QName("", "uf_Id"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
