/**
 * Cbr_Ifc_Ws_VwtelefoneRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.meta4.schemas.types;

public class Cbr_Ifc_Ws_VwtelefoneRecord  implements java.io.Serializable {
    private java.lang.String cbr_Complemento;

    private java.lang.String id_Organization;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String sco_Gb_Name;

    private java.util.Calendar std_Dt_End;

    private java.util.Calendar std_Dt_Start;

    private java.lang.String std_Id_Line_Type;

    private java.lang.String std_Id_Location_Type;

    private java.lang.String std_Id_Person;

    private java.lang.String std_Int_Country_Code;

    private java.lang.String std_Int_Region_Code;

    private java.lang.String std_Nat_Region_Code;

    private java.lang.Double std_Or_Phone;

    private java.lang.String std_Phone;

    public Cbr_Ifc_Ws_VwtelefoneRecord() {
    }

    public Cbr_Ifc_Ws_VwtelefoneRecord(
           java.lang.String cbr_Complemento,
           java.lang.String id_Organization,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String sco_Gb_Name,
           java.util.Calendar std_Dt_End,
           java.util.Calendar std_Dt_Start,
           java.lang.String std_Id_Line_Type,
           java.lang.String std_Id_Location_Type,
           java.lang.String std_Id_Person,
           java.lang.String std_Int_Country_Code,
           java.lang.String std_Int_Region_Code,
           java.lang.String std_Nat_Region_Code,
           java.lang.Double std_Or_Phone,
           java.lang.String std_Phone) {
           this.cbr_Complemento = cbr_Complemento;
           this.id_Organization = id_Organization;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.sco_Gb_Name = sco_Gb_Name;
           this.std_Dt_End = std_Dt_End;
           this.std_Dt_Start = std_Dt_Start;
           this.std_Id_Line_Type = std_Id_Line_Type;
           this.std_Id_Location_Type = std_Id_Location_Type;
           this.std_Id_Person = std_Id_Person;
           this.std_Int_Country_Code = std_Int_Country_Code;
           this.std_Int_Region_Code = std_Int_Region_Code;
           this.std_Nat_Region_Code = std_Nat_Region_Code;
           this.std_Or_Phone = std_Or_Phone;
           this.std_Phone = std_Phone;
    }


    /**
     * Gets the cbr_Complemento value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return cbr_Complemento
     */
    public java.lang.String getCbr_Complemento() {
        return cbr_Complemento;
    }


    /**
     * Sets the cbr_Complemento value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param cbr_Complemento
     */
    public void setCbr_Complemento(java.lang.String cbr_Complemento) {
        this.cbr_Complemento = cbr_Complemento;
    }


    /**
     * Gets the id_Organization value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return id_Organization
     */
    public java.lang.String getId_Organization() {
        return id_Organization;
    }


    /**
     * Sets the id_Organization value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param id_Organization
     */
    public void setId_Organization(java.lang.String id_Organization) {
        this.id_Organization = id_Organization;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the sco_Gb_Name value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return sco_Gb_Name
     */
    public java.lang.String getSco_Gb_Name() {
        return sco_Gb_Name;
    }


    /**
     * Sets the sco_Gb_Name value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param sco_Gb_Name
     */
    public void setSco_Gb_Name(java.lang.String sco_Gb_Name) {
        this.sco_Gb_Name = sco_Gb_Name;
    }


    /**
     * Gets the std_Dt_End value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return std_Dt_End
     */
    public java.util.Calendar getStd_Dt_End() {
        return std_Dt_End;
    }


    /**
     * Sets the std_Dt_End value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param std_Dt_End
     */
    public void setStd_Dt_End(java.util.Calendar std_Dt_End) {
        this.std_Dt_End = std_Dt_End;
    }


    /**
     * Gets the std_Dt_Start value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return std_Dt_Start
     */
    public java.util.Calendar getStd_Dt_Start() {
        return std_Dt_Start;
    }


    /**
     * Sets the std_Dt_Start value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param std_Dt_Start
     */
    public void setStd_Dt_Start(java.util.Calendar std_Dt_Start) {
        this.std_Dt_Start = std_Dt_Start;
    }


    /**
     * Gets the std_Id_Line_Type value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return std_Id_Line_Type
     */
    public java.lang.String getStd_Id_Line_Type() {
        return std_Id_Line_Type;
    }


    /**
     * Sets the std_Id_Line_Type value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param std_Id_Line_Type
     */
    public void setStd_Id_Line_Type(java.lang.String std_Id_Line_Type) {
        this.std_Id_Line_Type = std_Id_Line_Type;
    }


    /**
     * Gets the std_Id_Location_Type value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return std_Id_Location_Type
     */
    public java.lang.String getStd_Id_Location_Type() {
        return std_Id_Location_Type;
    }


    /**
     * Sets the std_Id_Location_Type value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param std_Id_Location_Type
     */
    public void setStd_Id_Location_Type(java.lang.String std_Id_Location_Type) {
        this.std_Id_Location_Type = std_Id_Location_Type;
    }


    /**
     * Gets the std_Id_Person value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return std_Id_Person
     */
    public java.lang.String getStd_Id_Person() {
        return std_Id_Person;
    }


    /**
     * Sets the std_Id_Person value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param std_Id_Person
     */
    public void setStd_Id_Person(java.lang.String std_Id_Person) {
        this.std_Id_Person = std_Id_Person;
    }


    /**
     * Gets the std_Int_Country_Code value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return std_Int_Country_Code
     */
    public java.lang.String getStd_Int_Country_Code() {
        return std_Int_Country_Code;
    }


    /**
     * Sets the std_Int_Country_Code value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param std_Int_Country_Code
     */
    public void setStd_Int_Country_Code(java.lang.String std_Int_Country_Code) {
        this.std_Int_Country_Code = std_Int_Country_Code;
    }


    /**
     * Gets the std_Int_Region_Code value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return std_Int_Region_Code
     */
    public java.lang.String getStd_Int_Region_Code() {
        return std_Int_Region_Code;
    }


    /**
     * Sets the std_Int_Region_Code value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param std_Int_Region_Code
     */
    public void setStd_Int_Region_Code(java.lang.String std_Int_Region_Code) {
        this.std_Int_Region_Code = std_Int_Region_Code;
    }


    /**
     * Gets the std_Nat_Region_Code value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return std_Nat_Region_Code
     */
    public java.lang.String getStd_Nat_Region_Code() {
        return std_Nat_Region_Code;
    }


    /**
     * Sets the std_Nat_Region_Code value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param std_Nat_Region_Code
     */
    public void setStd_Nat_Region_Code(java.lang.String std_Nat_Region_Code) {
        this.std_Nat_Region_Code = std_Nat_Region_Code;
    }


    /**
     * Gets the std_Or_Phone value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return std_Or_Phone
     */
    public java.lang.Double getStd_Or_Phone() {
        return std_Or_Phone;
    }


    /**
     * Sets the std_Or_Phone value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param std_Or_Phone
     */
    public void setStd_Or_Phone(java.lang.Double std_Or_Phone) {
        this.std_Or_Phone = std_Or_Phone;
    }


    /**
     * Gets the std_Phone value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @return std_Phone
     */
    public java.lang.String getStd_Phone() {
        return std_Phone;
    }


    /**
     * Sets the std_Phone value for this Cbr_Ifc_Ws_VwtelefoneRecord.
     * 
     * @param std_Phone
     */
    public void setStd_Phone(java.lang.String std_Phone) {
        this.std_Phone = std_Phone;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Cbr_Ifc_Ws_VwtelefoneRecord)) return false;
        Cbr_Ifc_Ws_VwtelefoneRecord other = (Cbr_Ifc_Ws_VwtelefoneRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.cbr_Complemento==null && other.getCbr_Complemento()==null) || 
             (this.cbr_Complemento!=null &&
              this.cbr_Complemento.equals(other.getCbr_Complemento()))) &&
            ((this.id_Organization==null && other.getId_Organization()==null) || 
             (this.id_Organization!=null &&
              this.id_Organization.equals(other.getId_Organization()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.sco_Gb_Name==null && other.getSco_Gb_Name()==null) || 
             (this.sco_Gb_Name!=null &&
              this.sco_Gb_Name.equals(other.getSco_Gb_Name()))) &&
            ((this.std_Dt_End==null && other.getStd_Dt_End()==null) || 
             (this.std_Dt_End!=null &&
              this.std_Dt_End.equals(other.getStd_Dt_End()))) &&
            ((this.std_Dt_Start==null && other.getStd_Dt_Start()==null) || 
             (this.std_Dt_Start!=null &&
              this.std_Dt_Start.equals(other.getStd_Dt_Start()))) &&
            ((this.std_Id_Line_Type==null && other.getStd_Id_Line_Type()==null) || 
             (this.std_Id_Line_Type!=null &&
              this.std_Id_Line_Type.equals(other.getStd_Id_Line_Type()))) &&
            ((this.std_Id_Location_Type==null && other.getStd_Id_Location_Type()==null) || 
             (this.std_Id_Location_Type!=null &&
              this.std_Id_Location_Type.equals(other.getStd_Id_Location_Type()))) &&
            ((this.std_Id_Person==null && other.getStd_Id_Person()==null) || 
             (this.std_Id_Person!=null &&
              this.std_Id_Person.equals(other.getStd_Id_Person()))) &&
            ((this.std_Int_Country_Code==null && other.getStd_Int_Country_Code()==null) || 
             (this.std_Int_Country_Code!=null &&
              this.std_Int_Country_Code.equals(other.getStd_Int_Country_Code()))) &&
            ((this.std_Int_Region_Code==null && other.getStd_Int_Region_Code()==null) || 
             (this.std_Int_Region_Code!=null &&
              this.std_Int_Region_Code.equals(other.getStd_Int_Region_Code()))) &&
            ((this.std_Nat_Region_Code==null && other.getStd_Nat_Region_Code()==null) || 
             (this.std_Nat_Region_Code!=null &&
              this.std_Nat_Region_Code.equals(other.getStd_Nat_Region_Code()))) &&
            ((this.std_Or_Phone==null && other.getStd_Or_Phone()==null) || 
             (this.std_Or_Phone!=null &&
              this.std_Or_Phone.equals(other.getStd_Or_Phone()))) &&
            ((this.std_Phone==null && other.getStd_Phone()==null) || 
             (this.std_Phone!=null &&
              this.std_Phone.equals(other.getStd_Phone())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCbr_Complemento() != null) {
            _hashCode += getCbr_Complemento().hashCode();
        }
        if (getId_Organization() != null) {
            _hashCode += getId_Organization().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getSco_Gb_Name() != null) {
            _hashCode += getSco_Gb_Name().hashCode();
        }
        if (getStd_Dt_End() != null) {
            _hashCode += getStd_Dt_End().hashCode();
        }
        if (getStd_Dt_Start() != null) {
            _hashCode += getStd_Dt_Start().hashCode();
        }
        if (getStd_Id_Line_Type() != null) {
            _hashCode += getStd_Id_Line_Type().hashCode();
        }
        if (getStd_Id_Location_Type() != null) {
            _hashCode += getStd_Id_Location_Type().hashCode();
        }
        if (getStd_Id_Person() != null) {
            _hashCode += getStd_Id_Person().hashCode();
        }
        if (getStd_Int_Country_Code() != null) {
            _hashCode += getStd_Int_Country_Code().hashCode();
        }
        if (getStd_Int_Region_Code() != null) {
            _hashCode += getStd_Int_Region_Code().hashCode();
        }
        if (getStd_Nat_Region_Code() != null) {
            _hashCode += getStd_Nat_Region_Code().hashCode();
        }
        if (getStd_Or_Phone() != null) {
            _hashCode += getStd_Or_Phone().hashCode();
        }
        if (getStd_Phone() != null) {
            _hashCode += getStd_Phone().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Cbr_Ifc_Ws_VwtelefoneRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Cbr_Ifc_Ws_VwtelefoneRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("cbr_Complemento");
        elemField.setXmlName(new javax.xml.namespace.QName("", "cbr_Complemento"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("id_Organization");
        elemField.setXmlName(new javax.xml.namespace.QName("", "id_Organization"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Gb_Name");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Gb_Name"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Dt_End");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Dt_End"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Dt_Start");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Dt_Start"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Line_Type");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Line_Type"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Location_Type");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Location_Type"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Person");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Person"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Int_Country_Code");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Int_Country_Code"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Int_Region_Code");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Int_Region_Code"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Nat_Region_Code");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Nat_Region_Code"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Or_Phone");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Or_Phone"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Phone");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Phone"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
