/**
 * Dados_ExtratoRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.meta4.schemas.types;

public class Dados_ExtratoRecord  implements java.io.Serializable {
    private java.lang.Double codigo_Evento;

    private java.lang.String descricao_Evento;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.Double numero_Parcelas;

    private java.lang.Double numero_Parcelas_Pagas;

    private java.lang.Double sequencia;

    private java.lang.Double valor_Pago;

    private java.lang.Double valor_Parcela;

    private java.lang.Double valor_Total;

    public Dados_ExtratoRecord() {
    }

    public Dados_ExtratoRecord(
           java.lang.Double codigo_Evento,
           java.lang.String descricao_Evento,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.Double numero_Parcelas,
           java.lang.Double numero_Parcelas_Pagas,
           java.lang.Double sequencia,
           java.lang.Double valor_Pago,
           java.lang.Double valor_Parcela,
           java.lang.Double valor_Total) {
           this.codigo_Evento = codigo_Evento;
           this.descricao_Evento = descricao_Evento;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.numero_Parcelas = numero_Parcelas;
           this.numero_Parcelas_Pagas = numero_Parcelas_Pagas;
           this.sequencia = sequencia;
           this.valor_Pago = valor_Pago;
           this.valor_Parcela = valor_Parcela;
           this.valor_Total = valor_Total;
    }


    /**
     * Gets the codigo_Evento value for this Dados_ExtratoRecord.
     * 
     * @return codigo_Evento
     */
    public java.lang.Double getCodigo_Evento() {
        return codigo_Evento;
    }


    /**
     * Sets the codigo_Evento value for this Dados_ExtratoRecord.
     * 
     * @param codigo_Evento
     */
    public void setCodigo_Evento(java.lang.Double codigo_Evento) {
        this.codigo_Evento = codigo_Evento;
    }


    /**
     * Gets the descricao_Evento value for this Dados_ExtratoRecord.
     * 
     * @return descricao_Evento
     */
    public java.lang.String getDescricao_Evento() {
        return descricao_Evento;
    }


    /**
     * Sets the descricao_Evento value for this Dados_ExtratoRecord.
     * 
     * @param descricao_Evento
     */
    public void setDescricao_Evento(java.lang.String descricao_Evento) {
        this.descricao_Evento = descricao_Evento;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Dados_ExtratoRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Dados_ExtratoRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Dados_ExtratoRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Dados_ExtratoRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the numero_Parcelas value for this Dados_ExtratoRecord.
     * 
     * @return numero_Parcelas
     */
    public java.lang.Double getNumero_Parcelas() {
        return numero_Parcelas;
    }


    /**
     * Sets the numero_Parcelas value for this Dados_ExtratoRecord.
     * 
     * @param numero_Parcelas
     */
    public void setNumero_Parcelas(java.lang.Double numero_Parcelas) {
        this.numero_Parcelas = numero_Parcelas;
    }


    /**
     * Gets the numero_Parcelas_Pagas value for this Dados_ExtratoRecord.
     * 
     * @return numero_Parcelas_Pagas
     */
    public java.lang.Double getNumero_Parcelas_Pagas() {
        return numero_Parcelas_Pagas;
    }


    /**
     * Sets the numero_Parcelas_Pagas value for this Dados_ExtratoRecord.
     * 
     * @param numero_Parcelas_Pagas
     */
    public void setNumero_Parcelas_Pagas(java.lang.Double numero_Parcelas_Pagas) {
        this.numero_Parcelas_Pagas = numero_Parcelas_Pagas;
    }


    /**
     * Gets the sequencia value for this Dados_ExtratoRecord.
     * 
     * @return sequencia
     */
    public java.lang.Double getSequencia() {
        return sequencia;
    }


    /**
     * Sets the sequencia value for this Dados_ExtratoRecord.
     * 
     * @param sequencia
     */
    public void setSequencia(java.lang.Double sequencia) {
        this.sequencia = sequencia;
    }


    /**
     * Gets the valor_Pago value for this Dados_ExtratoRecord.
     * 
     * @return valor_Pago
     */
    public java.lang.Double getValor_Pago() {
        return valor_Pago;
    }


    /**
     * Sets the valor_Pago value for this Dados_ExtratoRecord.
     * 
     * @param valor_Pago
     */
    public void setValor_Pago(java.lang.Double valor_Pago) {
        this.valor_Pago = valor_Pago;
    }


    /**
     * Gets the valor_Parcela value for this Dados_ExtratoRecord.
     * 
     * @return valor_Parcela
     */
    public java.lang.Double getValor_Parcela() {
        return valor_Parcela;
    }


    /**
     * Sets the valor_Parcela value for this Dados_ExtratoRecord.
     * 
     * @param valor_Parcela
     */
    public void setValor_Parcela(java.lang.Double valor_Parcela) {
        this.valor_Parcela = valor_Parcela;
    }


    /**
     * Gets the valor_Total value for this Dados_ExtratoRecord.
     * 
     * @return valor_Total
     */
    public java.lang.Double getValor_Total() {
        return valor_Total;
    }


    /**
     * Sets the valor_Total value for this Dados_ExtratoRecord.
     * 
     * @param valor_Total
     */
    public void setValor_Total(java.lang.Double valor_Total) {
        this.valor_Total = valor_Total;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Dados_ExtratoRecord)) return false;
        Dados_ExtratoRecord other = (Dados_ExtratoRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.codigo_Evento==null && other.getCodigo_Evento()==null) || 
             (this.codigo_Evento!=null &&
              this.codigo_Evento.equals(other.getCodigo_Evento()))) &&
            ((this.descricao_Evento==null && other.getDescricao_Evento()==null) || 
             (this.descricao_Evento!=null &&
              this.descricao_Evento.equals(other.getDescricao_Evento()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.numero_Parcelas==null && other.getNumero_Parcelas()==null) || 
             (this.numero_Parcelas!=null &&
              this.numero_Parcelas.equals(other.getNumero_Parcelas()))) &&
            ((this.numero_Parcelas_Pagas==null && other.getNumero_Parcelas_Pagas()==null) || 
             (this.numero_Parcelas_Pagas!=null &&
              this.numero_Parcelas_Pagas.equals(other.getNumero_Parcelas_Pagas()))) &&
            ((this.sequencia==null && other.getSequencia()==null) || 
             (this.sequencia!=null &&
              this.sequencia.equals(other.getSequencia()))) &&
            ((this.valor_Pago==null && other.getValor_Pago()==null) || 
             (this.valor_Pago!=null &&
              this.valor_Pago.equals(other.getValor_Pago()))) &&
            ((this.valor_Parcela==null && other.getValor_Parcela()==null) || 
             (this.valor_Parcela!=null &&
              this.valor_Parcela.equals(other.getValor_Parcela()))) &&
            ((this.valor_Total==null && other.getValor_Total()==null) || 
             (this.valor_Total!=null &&
              this.valor_Total.equals(other.getValor_Total())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCodigo_Evento() != null) {
            _hashCode += getCodigo_Evento().hashCode();
        }
        if (getDescricao_Evento() != null) {
            _hashCode += getDescricao_Evento().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getNumero_Parcelas() != null) {
            _hashCode += getNumero_Parcelas().hashCode();
        }
        if (getNumero_Parcelas_Pagas() != null) {
            _hashCode += getNumero_Parcelas_Pagas().hashCode();
        }
        if (getSequencia() != null) {
            _hashCode += getSequencia().hashCode();
        }
        if (getValor_Pago() != null) {
            _hashCode += getValor_Pago().hashCode();
        }
        if (getValor_Parcela() != null) {
            _hashCode += getValor_Parcela().hashCode();
        }
        if (getValor_Total() != null) {
            _hashCode += getValor_Total().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Dados_ExtratoRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Dados_ExtratoRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("codigo_Evento");
        elemField.setXmlName(new javax.xml.namespace.QName("", "codigo_Evento"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("descricao_Evento");
        elemField.setXmlName(new javax.xml.namespace.QName("", "descricao_Evento"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("numero_Parcelas");
        elemField.setXmlName(new javax.xml.namespace.QName("", "numero_Parcelas"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("numero_Parcelas_Pagas");
        elemField.setXmlName(new javax.xml.namespace.QName("", "numero_Parcelas_Pagas"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sequencia");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sequencia"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("valor_Pago");
        elemField.setXmlName(new javax.xml.namespace.QName("", "valor_Pago"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("valor_Parcela");
        elemField.setXmlName(new javax.xml.namespace.QName("", "valor_Parcela"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("valor_Total");
        elemField.setXmlName(new javax.xml.namespace.QName("", "valor_Total"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
