/**
 * Cbr_Ifc_Ws_VwpessoaService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.meta4.schemas;

public interface Cbr_Ifc_Ws_VwpessoaService extends java.rmi.Remote {
    public com.meta4.schemas.types.Cbr_Pesquisar_LogradouroOutput CBR_PESQUISAR_LOGRADOURO(java.lang.String ARG_CEP, java.lang.String ARG_ID_PAIS, java.lang.String ARG_UF, java.lang.String ARG_DESC_LOGRADOURO, java.lang.String ARG_ID_LOGRADOURO, java.lang.String ARG_ID_BAIRRO, java.lang.String ARG_ID_CIDADE) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.M4LoadobjectOutput m4LoadObject(com.meta4.schemas.types.Cbr_Array_Id_HrBlock CBR_ARRAY_ID_HR, com.meta4.schemas.types.Cbr_Estado_CivilBlock CBR_ESTADO_CIVIL, com.meta4.schemas.types.Cbr_Ifc_Ws_VwpessoaBlock CBR_IFC_WS_VWPESSOA, com.meta4.schemas.types.Cbr_Ifc_Ws_VwenderecoBlock CBR_IFC_WS_VWENDERECO, com.meta4.schemas.types.Cbr_Ifc_Ws_VwtelefoneBlock CBR_IFC_WS_VWTELEFONE, com.meta4.schemas.types.Cbr_Ifc_Ws_VwdependenteBlock CBR_IFC_WS_VWDEPENDENTE, com.meta4.schemas.types.Cbr_Pesquisar_LogradouroBlock CBR_PESQUISAR_LOGRADOURO, com.meta4.schemas.types.Cbr_Ifc_Ws_Vwpessoa_BancoBlock CBR_IFC_WS_VWPESSOA_BANCO, com.meta4.schemas.types.Cbr_Pesq_Ult_Std_Id_PersonBlock CBR_PESQ_ULT_STD_ID_PERSON, com.meta4.schemas.types.Cbr_Pesquisar_Agencia_BancariaBlock CBR_PESQUISAR_AGENCIA_BANCARIA) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.NovoOutput NOVO(java.lang.String ARG_STD_ID_PERSON, java.lang.String ARG_SCO_GB_NAME, java.util.Calendar ARG_STD_DT_BIRTH, java.util.Calendar ARG_CBR_DT_MORTE, java.lang.String ARG_CBR_N_MAE, java.lang.String ARG_CBR_N_PAI, java.lang.String ARG_CBR_CPF, java.lang.String ARG_CBR_NRO_SIC, java.lang.String ARG_CBR_PIS_PASEP, java.lang.String ARG_CBR_NRO_CART_IDENT, java.lang.String ARG_CBR_ORG_EMIS_CIDENT, java.util.Calendar ARG_CBR_DT_EMIS_CIDENT, java.lang.String ARG_CBR_NRO_T_ELEITOR, java.lang.String ARG_CBR_ZONA_T_ELEIT, java.lang.String ARG_CBR_SEC_T_ELEIT, java.lang.String ARG_CBR_ID_SUB_GDIV_TE, java.lang.String ARG_CBR_ID_GEO_DIV_TE, java.lang.String ARG_CBR_ID_COUNTRY_TE, java.lang.String ARG_ESTADO_CIVIL) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.AlterarOutput ALTERAR(java.lang.String ARG_STD_ID_PERSON, java.lang.String ARG_SCO_GB_NAME, java.util.Calendar ARG_STD_DT_BIRTH, java.util.Calendar ARG_CBR_DT_MORTE, java.lang.String ARG_CBR_N_MAE, java.lang.String ARG_CBR_N_PAI, java.lang.String ARG_CBR_CPF, java.lang.String ARG_CBR_NRO_SIC, java.lang.String ARG_CBR_PIS_PASEP, java.lang.String ARG_CBR_NRO_CART_IDENT, java.lang.String ARG_CBR_ORG_EMIS_CIDENT, java.util.Calendar ARG_CBR_DT_EMIS_CIDENT, java.lang.String ARG_CBR_NRO_T_ELEITOR, java.lang.String ARG_CBR_ZONA_T_ELEIT, java.lang.String ARG_CBR_SEC_T_ELEIT, java.lang.String ARG_CBR_ID_SUB_GDIV_TE, java.lang.String ARG_CBR_ID_GEO_DIV_TE, java.lang.String ARG_CBR_ID_COUNTRY_TE, java.lang.String ARG_ESTADO_CIVIL) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.PesquisarOutput PESQUISAR(java.lang.String ARG_STD_ID_PERSON, java.lang.String ARG_NOME) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.Novo_BancoOutput NOVO_BANCO(java.lang.String ARG_SCO_ID_PERSON, java.lang.Double ARG_SCO_OR_ACCOUNT, java.util.Calendar ARG_SCO_DT_START, java.util.Calendar ARG_SCO_DT_END, java.lang.String ARG_SCO_ID_BANK_BRANCH, java.lang.String ARG_SCO_ENTITLED, java.lang.String ARG_SCO_ACCOUNT_NUMBER, java.lang.String ARG_SCO_ID_BANKTYPE, java.lang.String ARG_SCO_GB_BANK) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.Alterar_BancoOutput ALTERAR_BANCO(java.lang.String ARG_SCO_ID_PERSON, java.lang.Double ARG_SCO_OR_ACCOUNT, java.util.Calendar ARG_SCO_DT_START, java.util.Calendar ARG_SCO_DT_END, java.lang.String ARG_SCO_ID_BANK_BRANCH, java.lang.String ARG_SCO_ENTITLED, java.lang.String ARG_SCO_ACCOUNT_NUMBER, java.lang.String ARG_SCO_ID_BANKTYPE, java.lang.String ARG_SCO_GB_BANK) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.Novo_EnderecoOutput NOVO_ENDERECO(java.lang.String ARG_STD_ID_PERSON, java.lang.Double ARG_STD_OR_ADDRESS, java.util.Calendar ARG_STD_DT_START, java.util.Calendar ARG_STD_DT_END, java.lang.Double ARG_CBR_OR_LOGRADOURO, java.lang.String ARG_STD_ADDRESS_LINE_1, java.lang.String ARG_STD_ADDRESS_LINE_2, java.lang.String ARG_STD_ZIP_CODE, java.lang.String ARG_SCO_GB_ADDRESS, java.lang.String ARG_STD_ID_GEO_PLACE, java.lang.String ARG_STD_ID_SUB_GEO_DIV, java.lang.String ARG_STD_ID_GEO_DIV, java.lang.String ARG_STD_ID_COUNTRY, java.lang.String ARG_STD_ID_LOCATION_TYPE, java.lang.String ARG_STD_MAILING_CHECK) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.Novo_TelefoneOutput NOVO_TELEFONE(java.lang.String ARG_STD_ID_PERSON, java.lang.Double ARG_STD_OR_PHONE, java.lang.String ARG_STD_PHONE, java.util.Calendar ARG_STD_DT_START, java.util.Calendar ARG_STD_DT_END, java.lang.String ARG_STD_ID_LINE_TYPE, java.lang.String ARG_STD_INT_COUNTRY_CODE, java.lang.String ARG_STD_INT_REGION_CODE, java.lang.String ARG_CBR_COMPLEMENTO) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.Novo_DependenteOutput NOVO_DEPENDENTE(java.lang.String ARG_STD_ID_HR, java.lang.Double ARG_STD_OR_DEP_NB, java.util.Calendar ARG_STD_DT_START, java.util.Calendar ARG_STD_DT_END, java.lang.String ARG_STD_ID_DEP_TYPE, java.lang.String ARG_STD_ID_FAMILY_PERSON, java.lang.String ARG_STD_COMMENT) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.Pesquisar_BancoOutput PESQUISAR_BANCO(java.lang.String ARG_STD_ID_PERSON) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.Alterar_EnderecoOutput ALTERAR_ENDERECO(java.lang.String ARG_STD_ID_PERSON, java.lang.Double ARG_STD_OR_ADDRESS, java.util.Calendar ARG_STD_DT_START, java.util.Calendar ARG_STD_DT_END, java.lang.Double ARG_CBR_OR_LOGRADOURO, java.lang.String ARG_STD_ADDRESS_LINE_1, java.lang.String ARG_STD_ADDRESS_LINE_2, java.lang.String ARG_STD_ZIP_CODE, java.lang.String ARG_SCO_GB_ADDRESS, java.lang.String ARG_STD_ID_GEO_PLACE, java.lang.String ARG_STD_ID_SUB_GEO_DIV, java.lang.String ARG_STD_ID_GEO_DIV, java.lang.String ARG_STD_ID_COUNTRY, java.lang.String ARG_STD_ID_LOCATION_TYPE, java.lang.String ARG_STD_MAILING_CHECK) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.Alterar_TelefoneOutput ALTERAR_TELEFONE(java.lang.String ARG_STD_ID_PERSON, java.lang.Double ARG_STD_OR_PHONE, java.lang.String ARG_STD_PHONE, java.util.Calendar ARG_STD_DT_START, java.util.Calendar ARG_STD_DT_END, java.lang.String ARG_STD_ID_LINE_TYPE, java.lang.String ARG_STD_INT_COUNTRY_CODE, java.lang.String ARG_STD_INT_REGION_CODE, java.lang.String ARG_CBR_COMPLEMENTO) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.Alterar_DependenteOutput ALTERAR_DEPENDENTE(java.lang.String ARG_STD_ID_HR, java.lang.Double ARG_STD_OR_DEP_NB, java.util.Calendar ARG_STD_DT_START, java.util.Calendar ARG_STD_DT_END, java.lang.String ARG_STD_ID_DEP_TYPE, java.lang.String ARG_STD_ID_FAMILY_PERSON, java.lang.String ARG_STD_COMMENT) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.Pesquisar_EnderecoOutput PESQUISAR_ENDERECO(java.lang.String ARG_STD_ID_PERSON) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.Pesquisar_TelefoneOutput PESQUISAR_TELEFONE(java.lang.String ARG_STD_ID_PERSON, java.lang.String ARG_SCO_GB_NAME) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.Pesquisar_DependenteOutput PESQUISAR_DEPENDENTE(java.lang.String ARG_STD_ID_HR) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public com.meta4.schemas.types.Pesquisar_Agencia_BancariaOutput PESQUISAR_AGENCIA_BANCARIA(java.lang.String ARG_CBR_ID_BANCO) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
    public int retrieveM4Session(java.lang.String in0) throws java.rmi.RemoteException, com.meta4.soapservices.exception.M4SoapException;
}
